run: when_changed
tasks:
  test:debug:
    aliases:
      - test
      - t
    cmds:
      - buck2 test -m debug //lib-hex-rs:test
  test:debug:watch:
    aliases:
      - test:watch
      - tw
    cmds:
      - buck2 run -m {{.TASK_WATCHMAN_CLIENT_MODE}} //dev-watchman-client -- --target
        //lib-hex-rs:test
  test:release:
    aliases:
      - tr
    cmds:
      - buck2 test -m release //lib-hex-rs:test
vars:
  NAME: lib-hex-rs
version: "3"
