# Do not manually edit this file, it is managed by Gleam.
#
# This file locks the dependency versions used, to make your build
# deterministic and to prevent unexpected versions from being included
# in your application.
#
# You should check this file into your source control repository.

packages = [
  { name = "gleam_stdlib", version = "1.0.5", build_tools = ["gleam"], requirements = [], source = "local", path = "../vendor/gleam_stdlib-1.0.5" },
  { name = "symbolize_dev_browser_test", version = "0.1.0", build_tools = ["gleam"], requirements = ["gleam_stdlib", "symbolize_lib_dataflow"], source = "local", path = "../dev-browser-test" },
  { name = "symbolize_lib_collection", version = "0.1.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], source = "local", path = "../lib-collection" },
  { name = "symbolize_lib_dataflow", version = "0.1.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], source = "local", path = "../lib-dataflow" },
  { name = "symbolize_lib_error", version = "0.1.0", build_tools = ["gleam"], requirements = ["gleam_stdlib", "symbolize_dev_browser_test", "symbolize_lib_dataflow", "symbolize_lib_random", "symbolize_lib_time"], source = "local", path = "../lib-error" },
  { name = "symbolize_lib_hex", version = "0.1.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], source = "local", path = "../lib-hex" },
  { name = "symbolize_lib_markup", version = "0.1.0", build_tools = ["gleam"], requirements = ["gleam_stdlib", "symbolize_dev_browser_test", "symbolize_lib_dataflow", "symbolize_lib_error", "symbolize_lib_styling"], source = "local", path = "../lib-markup" },
  { name = "symbolize_lib_payload", version = "0.1.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], source = "local", path = "../lib-payload" },
  { name = "symbolize_lib_random", version = "0.1.0", build_tools = ["gleam"], requirements = ["gleam_stdlib", "symbolize_lib_hex"], source = "local", path = "../lib-random" },
  { name = "symbolize_lib_stream", version = "0.1.0", build_tools = ["gleam"], requirements = ["gleam_stdlib", "symbolize_dev_browser_test", "symbolize_lib_dataflow", "symbolize_lib_error", "symbolize_lib_hex", "symbolize_lib_random", "symbolize_lib_time"], source = "local", path = "../lib-stream" },
  { name = "symbolize_lib_styling", version = "0.1.0", build_tools = ["gleam"], requirements = ["gleam_stdlib", "symbolize_lib_dataflow"], source = "local", path = "../lib-styling" },
  { name = "symbolize_lib_time", version = "0.1.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], source = "local", path = "../lib-time" },
  { name = "symbolize_svc_auth_guest_read", version = "0.1.0", build_tools = ["gleam"], requirements = ["gleam_stdlib", "symbolize_dev_browser_test", "symbolize_lib_dataflow", "symbolize_lib_stream", "symbolize_lib_time"], source = "local", path = "../svc-auth-guest-read" },
  { name = "symbolize_svc_auth_guest_view", version = "0.1.0", build_tools = ["gleam"], requirements = ["gleam_stdlib", "symbolize_dev_browser_test", "symbolize_lib_dataflow", "symbolize_lib_markup", "symbolize_lib_stream", "symbolize_lib_styling", "symbolize_lib_time"], source = "local", path = "../svc-auth-guest-view" },
]

[requirements]
gleam_stdlib = { path = "../vendor/gleam_stdlib-1.0.5" }
symbolize_dev_browser_test = { path = "../dev-browser-test" }
symbolize_lib_collection = { path = "../lib-collection" }
symbolize_lib_dataflow = { path = "../lib-dataflow" }
symbolize_lib_error = { path = "../lib-error" }
symbolize_lib_hex = { path = "../lib-hex" }
symbolize_lib_markup = { path = "../lib-markup" }
symbolize_lib_payload = { path = "../lib-payload" }
symbolize_lib_random = { path = "../lib-random" }
symbolize_lib_stream = { path = "../lib-stream" }
symbolize_lib_styling = { path = "../lib-styling" }
symbolize_lib_time = { path = "../lib-time" }
symbolize_svc_auth_guest_read = { path = "../svc-auth-guest-read" }
symbolize_svc_auth_guest_view = { path = "../svc-auth-guest-view" }
