[advisories]
db-path = "build/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]

[licenses]
allow = ["Apache-2.0", "BSD-3-Clause", "ISC", "LicenseRef-ring", "MIT", "Unicode-DFS-2016", "Unlicense"]
confidence-threshold = 0.8

[[licenses.clarify]]
crate = "ring"
expression = "LicenseRef-ring"
license-files = [{path = "LICENSE", hash = 0xbd0eed23}]

[licenses.private]
ignore = true

[bans]
multiple-versions = "deny"
wildcards = "deny"
skip-tree = ["watchman_client@0.8.0"]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
