watchman__server: task watchman:server
cargo__build__clippy: task cargo:build:clippy:watch
node__esbuild__build: task node:esbuild:build:watch
node__test: task node:test:watch
node__eslint__lint__check: task node:eslint:lint:check:watch
cabal__build: task cabal:build:watch
cabal__lint: task cabal:lint:watch
dev-gen__test: task dev-gen:test:watch
dev-cargo-build__test: task dev-cargo-build:test:watch
dev-sim__test: task dev-sim:test:watch
dev-watchman-client__test: task dev-watchman-client:test:watch
lib-hex-rs__test: task lib-hex-rs:test:watch
svc-gateway-host-run__test: task svc-gateway-host-run:test:watch
svc-gateway-host-run__run: task svc-gateway-host-run:run:watch
svc-search-host-read__test: task svc-search-host-read:test:watch
svc-search-host-read__run: task svc-search-host-read:run:watch
