includes:
  cargo:
    taskfile: dev-task/cargo.yml
  dev-cargo-build:
    taskfile: dev-cargo-build
  dev-esbuild:
    taskfile: dev-esbuild
  dev-eslint:
    taskfile: dev-eslint
  dev-gen:
    taskfile: dev-gen
  dev-nix-shell:
    internal: true
    taskfile: dev-nix-shell
  dev-node-loader:
    taskfile: dev-node-loader
  dev-node-suppress:
    taskfile: dev-node-suppress
  dev-pnpm-test:
    taskfile: dev-pnpm-test
  dev-prettier:
    taskfile: dev-prettier
  dev-stack-bin:
    internal: true
    taskfile: dev-stack-bin
  dev-tsconfig:
    taskfile: dev-tsconfig
  dev-watchman-client:
    taskfile: dev-watchman-client
  easyrsa:
    taskfile: dev-task/easyrsa.yml
  font:
    taskfile: dev-task/font.yml
  lib-collection:
    taskfile: lib-collection
  lib-compute:
    taskfile: lib-compute
  lib-concurrency:
    taskfile: lib-concurrency
  lib-contrast:
    taskfile: lib-contrast
  lib-convey:
    taskfile: lib-convey
  lib-error:
    taskfile: lib-error
  lib-hex-rs:
    taskfile: lib-hex-rs
  lib-hex-ts:
    taskfile: lib-hex-ts
  lib-payload:
    taskfile: lib-payload
  lib-random:
    taskfile: lib-random
  lib-stream:
    taskfile: lib-stream
  lib-test:
    taskfile: lib-test
  lib-test-runner:
    taskfile: lib-test-runner
  lib-time:
    taskfile: lib-time
  nix:
    taskfile: dev-task/nix.yml
  overmind:
    taskfile: dev-task/overmind.yml
  pnpm:
    taskfile: dev-task/pnpm.yml
  sqlite:
    taskfile: dev-task/sqlite.yml
  stack:
    taskfile: dev-task/stack.yml
  svc-auth-guest-read:
    taskfile: svc-auth-guest-read
  svc-auth-guest-view:
    taskfile: svc-auth-guest-view
  svc-gateway-guest-run:
    taskfile: svc-gateway-guest-run
  svc-gateway-host-run:
    taskfile: svc-gateway-host-run
  svc-gateway-host-store:
    taskfile: svc-gateway-host-store
  svc-search-host-read:
    taskfile: svc-search-host-read
  tmpfs:
    taskfile: dev-task/tmpfs.yml
  watchman:
    taskfile: dev-task/watchman.yml
run: when_changed
tasks:
  build:debug:
    aliases:
      - build
      - b
    deps:
      - cargo:build:debug
      - pnpm:build:debug
      - stack:build:debug
  build:release:
    aliases:
      - br
    deps:
      - cargo:build:release
      - pnpm:build:release
      - stack:build:release
  cargo:test:debug:
    aliases:
      - cargo:test
      - cargo:t
    deps:
      - dev-cargo-build:test:debug
      - dev-watchman-client:test:debug
      - lib-hex-rs:test:debug
      - svc-gateway-host-run:test:debug
      - svc-search-host-read:test:debug
  cargo:test:release:
    aliases:
      - cargo:tr
    deps:
      - dev-cargo-build:test:release
      - dev-watchman-client:test:release
      - lib-hex-rs:test:release
      - svc-gateway-host-run:test:release
      - svc-search-host-read:test:release
  check:
    aliases:
      - c
    cmds:
      - echo "✅"
    deps:
      - build:release
      - gen:check
      - test:release
      - format:check
      - lint:check
      - lock:check
  clean:
    deps:
      - cargo:clean
      - pnpm:clean
      - stack:clean
  dev:
    aliases:
      - d
    cmd:
      task: overmind:start
    deps:
      - watchman:client:prep
  format:check:
    aliases:
      - fc
    deps:
      - cargo:format:check
      - pnpm:format:check
      - stack:format:check
  format:fix:
    aliases:
      - format
      - f
    deps:
      - cargo:format:fix
      - pnpm:format:fix
      - stack:format:fix
  gen:
    aliases:
      - g
    cmd:
      task: stack:execute-target:run:{{.TASK_GEN_MODE}}
      vars:
        NAME: dev-gen
  gen:check:
    cmd:
      task: stack:execute-target:run:{{.TASK_GEN_MODE}}
      vars:
        ARGS: --check
        NAME: dev-gen
  install:
    aliases:
      - i
    deps:
      - cargo:install
      - font:install
      - pnpm:install
      - stack:install
  lint:check:
    aliases:
      - lint
      - l
    deps:
      - cargo:lint:check
      - pnpm:lint:check
      - sqlite:lint:check
      - stack:lint
  lint:fix:
    aliases:
      - lf
    deps:
      - cargo:lint:fix
      - pnpm:lint:fix
      - sqlite:lint:fix
      - stack:lint
  lock:check:
    deps:
      - cargo:lock:check
      - pnpm:lock:check
  pnpm:link-build-dirs:
    deps:
      - dev-esbuild:link-build-dir
      - dev-node-loader:link-build-dir
      - dev-node-suppress:link-build-dir
      - dev-pnpm-test:link-build-dir
      - dev-prettier:link-build-dir
      - dev-tsconfig:link-build-dir
      - dev-eslint:link-build-dir
      - lib-collection:link-build-dir
      - lib-compute:link-build-dir
      - lib-concurrency:link-build-dir
      - lib-contrast:link-build-dir
      - lib-convey:link-build-dir
      - lib-error:link-build-dir
      - lib-hex-ts:link-build-dir
      - lib-payload:link-build-dir
      - lib-random:link-build-dir
      - lib-stream:link-build-dir
      - lib-test:link-build-dir
      - lib-test-runner:link-build-dir
      - lib-time:link-build-dir
      - svc-auth-guest-read:link-build-dir
      - svc-auth-guest-view:link-build-dir
      - svc-gateway-guest-run:link-build-dir
  security:
    aliases:
      - s
    deps:
      - cargo:security
  test:release:
    aliases:
      - tr
    deps:
      - cargo:test:release
      - pnpm:test
      - stack:test:release
version: '3'
