version: '3'
run: when_changed
tasks:
  check:
    cmd: buck2 build //dev-browser-test:check
  format:check:
    aliases:
    - fc
    cmd: buck2 build //dev-browser-test:format-check
  build:
    dir: '{{.TASKFILE_DIR}}'
    cmd: gleam build
  link-build-dir:
    cmd:
      task: :build-dir:link-package-build-dir
      vars:
        NAME: '{{.NAME}}'
  lint:
    aliases:
    - l
    cmd: buck2 build //dev-browser-test:lint
vars:
  NAME: dev-browser-test
