version: '3'
run: when_changed
tasks:
  check:
    cmd: buck2 build //dev-browser-test:check
  format:check:
    aliases:
    - fc
    cmd: buck2 build //dev-browser-test:format-check
  build:
    dir: '{{.TASKFILE_DIR}}'
    cmd: gleam build
  lint:
    aliases:
    - l
    cmd: buck2 build //dev-browser-test:lint
