run: when_changed
tasks:
  test:debug:
    aliases:
      - test
      - t
    cmds:
      - buck2 test -m debug //dev-sim:test
  test:debug:watch:
    aliases:
      - test:watch
      - tw
    cmds:
      - buck2 run -m {{.TASK_WATCHMAN_CLIENT_MODE}} //dev-watchman-client -- --target
        //dev-sim:test
  test:release:
    aliases:
      - tr
    cmds:
      - buck2 test -m release //dev-sim:test
version: "3"
