load("@prelude//rules.bzl", "export_file")

export_file(
    name = "base.yaml",
    src = "base.yaml",
    visibility = ["PUBLIC"],
)

export_file(
    name = "relude-hlint.yaml",
    src = "relude-hlint.yaml",
    visibility = ["PUBLIC"],
)
