run: when_changed
tasks:
  run:debug:
    aliases:
      - run
      - r
    cmds:
      - buck2 run -m debug //svc-gateway-host-run -- {{.CLI_ARGS}}
  run:debug:watch:
    aliases:
      - run:watch
      - rw
    cmds:
      - buck2 run -m {{.TASK_WATCHMAN_CLIENT_MODE}} //dev-watchman-client -- --target
        //svc-gateway-host-run --restart -- {{.CLI_ARGS}}
  run:release:
    aliases:
      - rr
    cmds:
      - buck2 run -m release //svc-gateway-host-run -- {{.CLI_ARGS}}
  test:debug:
    aliases:
      - test
      - t
    cmds:
      - buck2 test -m debug //svc-gateway-host-run:test
  test:debug:watch:
    aliases:
      - test:watch
      - tw
    cmds:
      - buck2 run -m {{.TASK_WATCHMAN_CLIENT_MODE}} //dev-watchman-client -- --target
        //svc-gateway-host-run:test
  test:release:
    aliases:
      - tr
    cmds:
      - buck2 test -m release //svc-gateway-host-run:test
vars:
  NAME: svc-gateway-host-run
version: "3"
