load("@dev_buck//:rules.bzl", "alias", "format_check", "haskell_binary", "haskell_format_diff", "haskell_library", "haskell_lint", "haskell_test")

haskell_library(
    name = "symbolize-dev-gen",
    package_name = "symbolize-dev-gen",
    package_version = "0.0.0",
    srcs = glob(["src/**/*.hs"]),
    src_dirs = ["src"],
    default_language = "GHC2021",
    default_extensions = [
        "ExplicitNamespaces",
        "TypeFamilies",
        "DataKinds",
        "NoImplicitPrelude",
        "OverloadedStrings",
        "OverloadedLabels",
        "DerivingStrategies",
        "DeriveGeneric",
        "DuplicateRecordFields",
        "NoFieldSelectors",
        "NamedFieldPuns",
        "OverloadedRecordDot",
        "DisambiguateRecordFields",
        "OverloadedLists",
    ],
    deps = [
        "vendor//:aeson",
        "vendor//:base",
        "vendor//:bytestring",
        "vendor//:containers",
        "vendor//:directory",
        "vendor//:filepath",
        "vendor//:optparse-applicative",
        "vendor//:relude",
        "vendor//:text",
        "vendor//:toml-parser",
        "vendor//:typed-process",
        "vendor//:unliftio",
        "vendor//:unliftio-core",
        "vendor//:vector",
        "vendor//:yaml",
    ],
    compiler_flags = ["-Wall"],
    visibility = ["PUBLIC"],
)

haskell_binary(
    name = "symbolize-dev-gen-exe",
    main = "app/Main.hs",
    srcs = [],
    src_dirs = ["app"],
    default_language = "GHC2021",
    default_extensions = [
        "ExplicitNamespaces",
        "TypeFamilies",
        "DataKinds",
        "NoImplicitPrelude",
        "OverloadedStrings",
        "OverloadedLabels",
        "DerivingStrategies",
        "DeriveGeneric",
        "DuplicateRecordFields",
        "NoFieldSelectors",
        "NamedFieldPuns",
        "OverloadedRecordDot",
        "DisambiguateRecordFields",
        "OverloadedLists",
    ],
    compiler_flags = [
        "-Wall",
        "-threaded",
        "-rtsopts",
        "-with-rtsopts=-N",
    ],
    deps = [
        ":symbolize-dev-gen",
        "vendor//:aeson",
        "vendor//:base",
        "vendor//:bytestring",
        "vendor//:containers",
        "vendor//:directory",
        "vendor//:filepath",
        "vendor//:optparse-applicative",
        "vendor//:relude",
        "vendor//:text",
        "vendor//:toml-parser",
        "vendor//:typed-process",
        "vendor//:unliftio",
        "vendor//:unliftio-core",
        "vendor//:vector",
        "vendor//:yaml",
    ],
    visibility = ["PUBLIC"],
)

haskell_test(
    name = "symbolize-dev-gen-test",
    main = "test/Spec.hs",
    srcs = glob(["test/Dev/**/*.hs"]),
    src_dirs = ["test"],
    default_language = "GHC2021",
    default_extensions = [
        "ExplicitNamespaces",
        "TypeFamilies",
        "DataKinds",
        "NoImplicitPrelude",
        "OverloadedStrings",
        "OverloadedLabels",
        "DerivingStrategies",
        "DeriveGeneric",
        "DuplicateRecordFields",
        "NoFieldSelectors",
        "NamedFieldPuns",
        "OverloadedRecordDot",
        "DisambiguateRecordFields",
        "OverloadedLists",
    ],
    compiler_flags = [
        "-Wall",
        "-threaded",
        "-rtsopts",
        "-with-rtsopts=-N",
    ],
    deps = [
        ":symbolize-dev-gen",
        "vendor//:aeson",
        "vendor//:base",
        "vendor//:bytestring",
        "vendor//:containers",
        "vendor//:directory",
        "vendor//:filepath",
        "vendor//:hspec",
        "vendor//:optparse-applicative",
        "vendor//:relude",
        "vendor//:text",
        "vendor//:toml-parser",
        "vendor//:typed-process",
        "vendor//:unliftio",
        "vendor//:unliftio-core",
        "vendor//:vector",
        "vendor//:yaml",
    ],
    visibility = ["PUBLIC"],
)

alias(
    name = "test",
    actual = ":symbolize-dev-gen-test",
    visibility = ["PUBLIC"],
)

alias(
    name = "dev-gen",
    actual = ":symbolize-dev-gen-exe",
    visibility = ["PUBLIC"],
)

alias(
    name = "check",
    actual = ":symbolize-dev-gen-exe",
    visibility = ["PUBLIC"],
)

haskell_format_diff(
    name = "format-diff",
    srcs = glob(["app/**/*.hs", "src/**/*.hs", "test/**/*.hs"]),
    visibility = ["PUBLIC"],
)

format_check(
    name = "format-check",
    diff = ":format-diff",
    visibility = ["PUBLIC"],
)

haskell_lint(
    name = "lint",
    srcs = glob(["app/**/*.hs", "src/**/*.hs", "test/**/*.hs"]),
    targets = [
        ":symbolize-dev-gen",
        ":symbolize-dev-gen-exe",
        ":symbolize-dev-gen-test",
    ],
    visibility = ["PUBLIC"],
)

alias(
    name = "clippy",
    actual = ":lint",
    visibility = ["PUBLIC"],
)

