name: symbolize-dev-gen
version: 0.0.0

dependencies:
  - base == 4.19.2.0
  - aeson == 2.2.3.0
  - filepath == 1.4.301.0
  - optparse-applicative == 0.18.1.0
  - relude == 1.2.2.0
  - toml-parser == 1.3.2.0
  - typed-process == 0.2.13.0
  - unliftio == 0.2.25.1
  - unliftio-core == 0.2.1.0
  - vector == 0.13.2.0
  - yaml == 0.11.11.2

language: GHC2021

default-extensions:
  - ExplicitNamespaces
  - TypeFamilies
  - DataKinds
  - NoImplicitPrelude
  - OverloadedStrings
  - OverloadedLabels
  - DerivingStrategies
  - DeriveGeneric
  - DuplicateRecordFields
  - NoFieldSelectors
  - NamedFieldPuns
  - OverloadedRecordDot
  - DisambiguateRecordFields
  - OverloadedLists

library:
  source-dirs: src

executables:
  symbolize-dev-gen-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - symbolize-dev-gen

tests:
  symbolize-dev-gen-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - symbolize-dev-gen
      - hspec
