version: '3'

run: when_changed

vars:
  NAME: dev-gen

tasks:
  test:debug:
    aliases:
      - test
      - t
    cmd: buck2 test //dev-gen:symbolize-dev-gen-test

  test:debug:watch:
    aliases:
      - test:watch
      - tw
    cmd:
      task: :watchman:client
      vars:
        WATCH: true
        RESTART: false
        MODE: haskell
        COMMAND: buck2 test //dev-gen:symbolize-dev-gen-test

  test:release:
    aliases:
      - tr
    cmd: buck2 test //dev-gen:symbolize-dev-gen-test

  link-build-dir:
    cmd:
      task: :build-dir:link-package-build-dir
      vars:
        NAME: '{{.NAME}}'
