version: '3'

run: when_changed

vars:
  NAME: dev-gen

tasks:
  test:debug:
    aliases:
      - test
      - t
    cmd: buck2 test -m debug //dev-gen:test

  test:debug:watch:
    aliases:
      - test:watch
      - tw
    cmd: buck2 run -m {{.TASK_WATCHMAN_CLIENT_MODE}} //dev-watchman-client -- --target //dev-gen:test

  test:release:
    aliases:
      - tr
    cmd: buck2 test -m release //dev-gen:test

  check:
    cmd: buck2 build -m debug //dev-gen:check

  format:check:
    aliases:
      - fc
    cmd: buck2 build //dev-gen:format-check

  format:fix:
    aliases:
      - format
      - f
    cmd: ./dev-buck/format-fix.sh

  lint:
    aliases:
      - l
    cmd: buck2 build //dev-gen:lint

  link-build-dir:
    cmd:
      task: :build-dir:link-package-build-dir
      vars:
        NAME: '{{.NAME}}'
