# Starlark rules for Haskell compilation using Buck2 and GHC

HaskellLibraryInfo = provider(fields = [
    "package_name",
    "package_id",
    "is_boot",
    "pkg_dir",
    "direct_dep_ids",
    "transitive_nodes",
    "transitive_pkg_dirs",
    "transitive_package_ids",
    "transitive_boot_pkgs",
    "transitive_include_dirs",
    "transitive_extra_libs",
])

def _get_pkg_dir_path(label: Label) -> str:
    pkg = label.package
    if label.cell != "root":
        cell_name = label.cell.replace("_", "-")
        return cell_name + ("/" + pkg if pkg else "")
    return pkg

def _parse_module_info(path: str, src_dirs: list[str]) -> struct:
    clean = path
    for d in src_dirs:
        prefix = d.rstrip("/") + "/"
        if clean.startswith(prefix):
            clean = clean[len(prefix):]
            break
        elif clean == d.rstrip("/"):
            clean = ""
            break
    if clean.endswith(".hs"):
        clean = clean[:-3]
    elif clean.endswith(".lhs"):
        clean = clean[:-4]

    dotted = clean.replace("/", ".")
    parts = clean.split("/")
    dir_path = "/".join(parts[:-1]) if len(parts) > 1 else ""
    file_base = parts[-1] if parts else ""

    return struct(
        dotted_name = dotted,
        rel_path = clean,
        dir_path = dir_path,
        file_base = file_base,
    )

def _version_components(v: str) -> list[int]:
    parts = []
    for x in v.split("."):
        if x.isdigit():
            parts.append(int(x))
        else:
            break
    for _ in range(3):
        if len(parts) < 3:
            parts.append(0)
    return [parts[0], parts[1], parts[2]]

def _topo_sort(modules: dict) -> list[str]:
    in_degree = {}
    dependents = {}
    for k, m in modules.items():
        deps_in_set = [d for d in m.deps if d in modules]
        in_degree[k] = len(deps_in_set)
        for d in deps_in_set:
            if d not in dependents:
                dependents[d] = []
            dependents[d].append(k)

    queue = [k for k, deg in in_degree.items() if deg == 0]
    result = []
    for _ in range(len(modules) + 1):
        if not queue:
            break
        curr = queue[0]
        queue = queue[1:]
        result.append(curr)
        for dep in dependents.get(curr, []):
            in_degree[dep] = in_degree[dep] - 1
            if in_degree[dep] == 0:
                queue.append(dep)

    for k in modules:
        if k not in result:
            result.append(k)
    return result

def _topo_link_order(nodes: dict) -> list[str]:
    in_degree = {}
    dependencies = {}
    for pkg in nodes:
        in_degree[pkg] = 0
        dependencies[pkg] = []

    for pkg, data in nodes.items():
        for d in data.direct_dep_ids:
            if d in nodes:
                in_degree[d] = in_degree[d] + 1
                dependencies[pkg].append(d)

    queue = [k for k, deg in in_degree.items() if deg == 0]
    result = []
    for _ in range(len(nodes) + 1):
        if not queue:
            break
        curr = queue[0]
        queue = queue[1:]
        result.append(curr)
        for dep in dependencies.get(curr, []):
            in_degree[dep] = in_degree[dep] - 1
            if in_degree[dep] == 0:
                queue.append(dep)

    for k in nodes:
        if k not in result:
            result.append(k)
    return result

def _generate_cabal_macros(pkg_name: str, pkg_ver: str, dep_info) -> str:
    lines = ["/* Autogenerated cabal_macros.h */\n"]

    def add_pkg(name, ver):
        sanitized = name.replace("-", "_")
        v1, v2, v3 = _version_components(ver)
        lines.append("#ifndef VERSION_" + sanitized)
        lines.append('#define VERSION_' + sanitized + ' "' + ver + '"')
        lines.append("#endif\n")
        lines.append("#ifndef MIN_VERSION_" + sanitized)
        lines.append(
            "#define MIN_VERSION_" + sanitized + "(major1,major2,minor) (\\" +
            "\n  (major1) < " + str(v1) + " ||\\" +
            "\n  (major1) == " + str(v1) + " && (major2) < " + str(v2) + " ||\\" +
            "\n  (major1) == " + str(v1) + " && (major2) == " + str(v2) + " && (minor) <= " + str(v3) + ")"
        )
        lines.append("#endif\n")

    if pkg_name:
        add_pkg(pkg_name, pkg_ver)
        lines.append('#ifndef CURRENT_PACKAGE_VERSION\n#define CURRENT_PACKAGE_VERSION "' + pkg_ver + '"\n#endif\n')
        lines.append('#ifndef CURRENT_COMPONENT_ID\n#define CURRENT_COMPONENT_ID "' + pkg_name + '-' + pkg_ver + '"\n#endif\n')
        lines.append('#ifndef CURRENT_PACKAGE_KEY\n#define CURRENT_PACKAGE_KEY "' + pkg_name + '-' + pkg_ver + '"\n#endif\n')

    # Common boot package versions in GHC 9.8.4
    boot_versions = {
        "base": "4.19.2.0",
        "bytestring": "0.12.1.0",
        "containers": "0.6.8",
        "deepseq": "1.5.1.0",
        "directory": "1.3.8.5",
        "filepath": "1.4.301.0",
        "mtl": "2.3.1",
        "process": "1.6.25.0",
        "template-haskell": "2.21.0.0",
        "text": "2.1.1",
        "time": "1.12.2",
        "transformers": "0.6.1.0",
        "unix": "2.8.6.0",
    }
    for bp in dep_info.boot_pkgs:
        ver = boot_versions.get(bp, "1.0.0")
        add_pkg(bp, ver)

    for pid in dep_info.pkg_ids:
        parts = pid.rsplit("-", 1)
        if len(parts) == 2:
            add_pkg(parts[0], parts[1])

    return "\n".join(lines) + "\n"

def _collect_haskell_deps(deps: list[Dependency]):
    all_nodes = {}
    direct_dep_ids = []
    boot_pkgs = []
    include_dirs = []
    extra_libs = []

    for dep in deps:
        if HaskellLibraryInfo in dep:
            info = dep[HaskellLibraryInfo]
            if info.is_boot:
                if info.package_name and info.package_name not in boot_pkgs:
                    boot_pkgs.append(info.package_name)
            else:
                if info.package_id and info.package_id not in direct_dep_ids:
                    direct_dep_ids.append(info.package_id)
                for k, v in getattr(info, "transitive_nodes", {}).items():
                    if k not in all_nodes:
                        all_nodes[k] = v
                if info.package_id:
                    all_nodes[info.package_id] = struct(
                        pkg_dir = info.pkg_dir,
                        direct_dep_ids = getattr(info, "direct_dep_ids", []),
                    )

            for bp in info.transitive_boot_pkgs:
                if bp not in boot_pkgs:
                    boot_pkgs.append(bp)
            for inc in info.transitive_include_dirs:
                if inc not in include_dirs:
                    include_dirs.append(inc)
            for el in info.transitive_extra_libs:
                if el not in extra_libs:
                    extra_libs.append(el)

    sorted_pkg_ids = _topo_link_order(all_nodes)
    pkg_dirs = [all_nodes[pid].pkg_dir for pid in sorted_pkg_ids if all_nodes[pid].pkg_dir != None]

    return struct(
        pkg_dirs = pkg_dirs,
        pkg_ids = sorted_pkg_ids,
        boot_pkgs = boot_pkgs,
        include_dirs = include_dirs,
        extra_libs = extra_libs,
        direct_dep_ids = direct_dep_ids,
        transitive_nodes = all_nodes,
    )

def _build_ghc_dep_flags(dep_info) -> list:
    flags = []
    for pkg_dir in dep_info.pkg_dirs:
        flags.append(cmd_args(pkg_dir, format = "-package-db={}/package.conf.d"))
    for pid in dep_info.pkg_ids:
        flags.extend(["-package-id", pid])
    for bp in dep_info.boot_pkgs:
        flags.extend(["-package", bp])
    for inc in dep_info.include_dirs:
        flags.append(cmd_args(inc, format = "-I{}"))
    return flags

def _haskell_boot_package_impl(ctx: AnalysisContext) -> list[Provider]:
    pkg_name = ctx.attrs.package_name or ctx.attrs.name
    return [
        DefaultInfo(),
        HaskellLibraryInfo(
            package_name = pkg_name,
            package_id = "",
            is_boot = True,
            pkg_dir = None,
            direct_dep_ids = [],
            transitive_nodes = {},
            transitive_pkg_dirs = [],
            transitive_package_ids = [],
            transitive_boot_pkgs = [pkg_name],
            transitive_include_dirs = [],
            transitive_extra_libs = [],
        ),
    ]

haskell_boot_package = rule(
    impl = _haskell_boot_package_impl,
    attrs = {
        "package_name": attrs.string(default = ""),
    },
)

def declare_boot_packages():
    boot_packages = [
        "Cabal",
        "Cabal-syntax",
        "array",
        "base",
        "binary",
        "bytestring",
        "containers",
        "deepseq",
        "directory",
        "exceptions",
        "filepath",
        "ghc-bignum",
        "ghc-boot-th",
        "ghc-prim",
        "integer-gmp",
        "mtl",
        "parsec",
        "pretty",
        "process",
        "rts",
        "stm",
        "template-haskell",
        "text",
        "time",
        "transformers",
        "unix",
    ]
    for pkg in boot_packages:
        haskell_boot_package(
            name = pkg,
            package_name = pkg,
            visibility = ["PUBLIC"],
        )
        if "-" in pkg:
            haskell_boot_package(
                name = pkg.replace("-", "_"),
                package_name = pkg,
                visibility = ["PUBLIC"],
            )


def _haskell_library_impl(ctx: AnalysisContext) -> list[Provider]:
    pkg_name = ctx.attrs.package_name or ctx.attrs.name
    pkg_ver = ctx.attrs.package_version
    pkg_id = pkg_name + "-" + pkg_ver
    out_pkg = ctx.actions.declare_output(ctx.attrs.name, dir = True)

    src_dirs = ctx.attrs.src_dirs or ["."]
    dep_info = _collect_haskell_deps(ctx.attrs.deps)

    # Autogenerate cabal_macros.h
    cabal_macros_content = _generate_cabal_macros(pkg_name, pkg_ver, dep_info)
    cabal_macros = ctx.actions.write("cabal_macros.h", cabal_macros_content)

    pkg_dir_path = _get_pkg_dir_path(ctx.label)

    local_include_flags = []
    local_include_dirs = []
    for d in ctx.attrs.include_dirs:
        inc_p = pkg_dir_path + "/" + d if pkg_dir_path else d
        local_include_flags.append("-I" + inc_p)
        local_include_dirs.append(inc_p)

    # Compile C sources if any
    c_objs = []
    c_include_flags = list(local_include_flags)
    for inc in dep_info.include_dirs:
        c_include_flags.append(cmd_args(inc, format = "-I{}"))

    for c_src in ctx.attrs.c_srcs:
        c_obj = ctx.actions.declare_output("__c_obj__/" + c_src.short_path + ".o")
        c_cmd = cmd_args(
            "ghc",
            "-c",
            c_src,
            "-o",
            c_obj.as_output(),
            c_include_flags,
            ctx.attrs.compiler_flags,
        )
        ctx.actions.run(c_cmd, category = "haskell_c_compile", identifier = c_src.short_path)
        c_objs.append(c_obj)

    transitive_nodes = dict(dep_info.transitive_nodes)
    transitive_nodes[pkg_id] = struct(
        pkg_dir = out_pkg,
        direct_dep_ids = dep_info.direct_dep_ids,
    )
    dep_ids_str = " ".join(dep_info.direct_dep_ids)

    # Package assembly shell script
    pkg_assembly_sh = (
        'out_pkg="$1"; shift; pkg_name="$1"; shift; pkg_ver="$1"; shift; pkg_id="$1"; shift; ' +
        'exposed_mods="$1"; shift; extra_libs="$1"; shift; dep_ids="$1"; shift; num_inc_dirs="$1"; shift; ' +
        'inc_dirs=(); for ((i=0; i<num_inc_dirs; i++)); do inc_dirs+=("$1"); shift; done; ' +
        'num_mod_dirs="$1"; shift; ' +
        'mod_dirs=(); for ((i=0; i<num_mod_dirs; i++)); do mod_dirs+=("$1"); shift; done; ' +
        'num_c_objs="$1"; shift; c_objs=(); for ((i=0; i<num_c_objs; i++)); do c_objs+=("$1"); shift; done; ' +
        'mkdir -p "$out_pkg/lib"; ' +
        'mkdir -p "$out_pkg/include"; ' +
        'for inc in "${inc_dirs[@]}"; do if [ -d "$inc" ]; then cp -r "$inc"/* "$out_pkg/include/"; fi; done; ' +
        'rm -rf "$out_pkg/package.conf.d"; ' +
        'all_objs=(); ' +
        'for md in "${mod_dirs[@]}"; do ' +
        '  if [ -d "$md" ]; then cp -r "$md"/* "$out_pkg/lib/"; fi; ' +
        '  while IFS= read -r o_f; do if [ -n "$o_f" ]; then all_objs+=("$o_f"); fi; done < <(find "$md" -name "*.o" 2>/dev/null); ' +
        'done; ' +
        'for co in "${c_objs[@]}"; do all_objs+=("$co"); done; ' +
        'if [ ${#all_objs[@]} -gt 0 ]; then ar crs "$out_pkg/lib/libHS${pkg_id}.a" "${all_objs[@]}"; fi; ' +
        'ghc-pkg init "$out_pkg/package.conf.d"; ' +
        'cat << EOF > "$out_pkg/${pkg_id}.conf"\n' +
        'name: ${pkg_name}\nversion: ${pkg_ver}\nid: ${pkg_id}\nkey: ${pkg_id}\nexposed: True\n' +
        'exposed-modules: ${exposed_mods}\nimport-dirs: \\${pkgroot}/lib\nlibrary-dirs: \\${pkgroot}/lib\ninclude-dirs: \\${pkgroot}/include\n' +
        'hs-libraries: HS${pkg_id}\nEOF\n' +
        'if [ -n "$dep_ids" ]; then echo "depends: ${dep_ids}" >> "$out_pkg/${pkg_id}.conf"; fi; ' +
        'if [ -n "$extra_libs" ]; then echo "extra-libraries: ${extra_libs}" >> "$out_pkg/${pkg_id}.conf"; fi; ' +
        'if [ "${#mod_dirs[@]}" -gt 0 ]; then find "${mod_dirs[@]}" -name "*.warnings" -exec cat {} + > "$out_pkg/warnings.log" 2>/dev/null || true; fi; touch "$out_pkg/warnings.log"; ' +
        'ghc-pkg register --package-db="$out_pkg/package.conf.d" --no-expand-pkgroot --force "$out_pkg/${pkg_id}.conf"'
    )

    # If no Haskell sources, assemble package with C sources only
    if not ctx.attrs.srcs:
        c_cmd = cmd_args(
            "bash", "-e", "-c", pkg_assembly_sh, "--",
            out_pkg.as_output(),
            pkg_name,
            pkg_ver,
            pkg_id,
            " ".join(ctx.attrs.exposed_modules),
            " ".join(ctx.attrs.extra_libs),
            dep_ids_str,
            str(len(local_include_dirs)),
            local_include_dirs,
            "0", # num_mod_dirs
            str(len(c_objs)),
            c_objs,
        )
        ctx.actions.run(c_cmd, category = "haskell_pkg_assemble", identifier = pkg_name)
    else:
        # Step 1: Scan module dependencies
        deps_json = ctx.actions.declare_output("__deps__.json")
        scan_args = cmd_args(
            "python3",
            ctx.attrs._dep_scanner,
            "--out",
            deps_json.as_output(),
            "--",
        )
        scan_args.add("-this-unit-id", pkg_id)
        for d in src_dirs:
            scan_args.add("-i" + (pkg_dir_path + "/" + d if pkg_dir_path else d))
        if ctx.attrs.default_language:
            scan_args.add("-X" + ctx.attrs.default_language)
        for ext in ctx.attrs.default_extensions:
            scan_args.add("-X" + ext)
        scan_args.add(_build_ghc_dep_flags(dep_info))
        for inc_flag in local_include_flags:
            scan_args.add(inc_flag)
        for flag in ctx.attrs.compiler_flags:
            scan_args.add(flag)
        scan_args.add("-optP-include", cmd_args(cabal_macros, format = "-optP{}"))
        scan_args.add(ctx.attrs.srcs)

        ctx.actions.run(
            scan_args,
            category = "haskell_dep_scan",
            identifier = ctx.attrs.name,
        )

        # Step 2: Dynamic actions for module compilation and package assembly
        def dynamic_compile(ctx: AnalysisContext, artifacts, outputs):
            dep_graph = artifacts[deps_json].read_json()
            src_map = {src.short_path: src for src in ctx.attrs.srcs}

            modules = {}
            for mod_key, data in dep_graph.items():
                src_path = data["src"]
                matched_art = None
                for s_path, s_art in src_map.items():
                    if src_path.endswith(s_path) or s_path.endswith(src_path):
                        matched_art = s_art
                        break
                if not matched_art:
                    base = src_path.split("/")[-1]
                    for s_path, s_art in src_map.items():
                        if s_path.endswith(base):
                            matched_art = s_art
                            break
                if matched_art:
                    info = _parse_module_info(matched_art.short_path, src_dirs)
                    modules[mod_key] = struct(
                        info = info,
                        src = matched_art,
                        deps = data.get("deps", []),
                    )

            mod_dirs = {}
            for mod_key, mod in modules.items():
                mod_dirs[mod_key] = ctx.actions.declare_output("__mod__/" + mod.info.dotted_name, dir = True)

            # Compile each module in topological order
            ordered_keys = _topo_sort(modules)
            compiled_mod_dirs = []
            for mod_key in ordered_keys:
                mod = modules[mod_key]
                ghc_flags = ["-this-unit-id", pkg_id]
                for d in src_dirs:
                    ghc_flags.append("-i" + (pkg_dir_path + "/" + d if pkg_dir_path else d))

                for prev_dir in compiled_mod_dirs:
                    ghc_flags.append(cmd_args(prev_dir, format = "-i{}"))

                ghc_flags.extend(_build_ghc_dep_flags(dep_info))
                ghc_flags.extend(local_include_flags)

                if ctx.attrs.default_language:
                    ghc_flags.append("-X" + ctx.attrs.default_language)
                for ext in ctx.attrs.default_extensions:
                    ghc_flags.append("-X" + ext)
                for flag in ctx.attrs.compiler_flags:
                    ghc_flags.append(flag)

                ghc_flags.append("-optP-include")
                ghc_flags.append(cmd_args(cabal_macros, format = "-optP{}"))

                compile_cmd = cmd_args(
                    "bash",
                    "-e",
                    "-c",
                    'out_dir="$1"; shift; src="$1"; shift; rel_path="$1"; shift; dir_path="$1"; shift; ' +
                    'src_dir="$(dirname "$src")"; mkdir -p "$out_dir/$dir_path"; ' +
                    'warn_file="$out_dir/$rel_path.warnings"; ' +
                    'set +e; ghc -c "$src" -I"$src_dir" -o "$out_dir/$rel_path.o" -ohi "$out_dir/$rel_path.hi" "$@" 2> "$warn_file"; status=$?; ' +
                    'if [ -s "$warn_file" ]; then cat "$warn_file" >&2; fi; exit $status',
                    "--",
                    mod_dirs[mod_key].as_output(),
                    mod.src,
                    mod.info.rel_path,
                    mod.info.dir_path,
                    ghc_flags,
                )

                ctx.actions.run(
                    compile_cmd,
                    category = "haskell_compile",
                    identifier = mod.info.dotted_name,
                )
                compiled_mod_dirs.append(mod_dirs[mod_key])

            # Assemble package
            all_mod_dirs = [mod_dirs[k] for k in mod_dirs]
            exposed = ctx.attrs.exposed_modules or [mod.info.dotted_name for mod in modules.values()]

            assemble_args = cmd_args(
                "bash",
                "-e",
                "-c",
                pkg_assembly_sh,
                "--",
                outputs[out_pkg].as_output(),
                pkg_name,
                pkg_ver,
                pkg_id,
                " ".join(exposed),
                " ".join(ctx.attrs.extra_libs),
                dep_ids_str,
                str(len(local_include_dirs)),
                local_include_dirs,
                str(len(all_mod_dirs)),
                all_mod_dirs,
                str(len(c_objs)),
                c_objs,
            )

            ctx.actions.run(
                assemble_args,
                category = "haskell_pkg_assemble",
                identifier = pkg_name,
            )

        ctx.actions.dynamic_output(
            dynamic = [deps_json],
            inputs = ctx.attrs.srcs + dep_info.pkg_dirs + c_objs + [cabal_macros],
            outputs = [out_pkg.as_output()],
            f = dynamic_compile,
        )

    warnings_art = out_pkg.project("warnings.log")
    return [
        DefaultInfo(
            default_output = out_pkg,
            sub_targets = {
                "warnings": [DefaultInfo(default_output = warnings_art)],
            },
        ),
        HaskellLibraryInfo(
            package_name = pkg_name,
            package_id = pkg_id,
            is_boot = False,
            pkg_dir = out_pkg,
            direct_dep_ids = dep_info.direct_dep_ids,
            transitive_nodes = transitive_nodes,
            transitive_pkg_dirs = [out_pkg] + dep_info.pkg_dirs,
            transitive_package_ids = [pkg_id] + dep_info.pkg_ids,
            transitive_boot_pkgs = dep_info.boot_pkgs,
            transitive_include_dirs = dep_info.include_dirs + ([cmd_args(out_pkg, format = "{}/include")] if ctx.attrs.include_dirs else []),
            transitive_extra_libs = dep_info.extra_libs + ctx.attrs.extra_libs,
        ),
    ]

haskell_library = rule(
    impl = _haskell_library_impl,
    attrs = {
        "srcs": attrs.list(attrs.source(), default = []),
        "package_name": attrs.string(default = ""),
        "package_version": attrs.string(default = "0.1.0"),
        "src_dirs": attrs.list(attrs.string(), default = []),
        "deps": attrs.list(attrs.dep(), default = []),
        "c_srcs": attrs.list(attrs.source(), default = []),
        "includes": attrs.list(attrs.source(), default = []),
        "include_dirs": attrs.list(attrs.string(), default = []),
        "default_language": attrs.string(default = "Haskell2010"),
        "default_extensions": attrs.list(attrs.string(), default = []),
        "compiler_flags": attrs.list(attrs.string(), default = []),
        "exposed_modules": attrs.list(attrs.string(), default = []),
        "extra_libs": attrs.list(attrs.string(), default = []),
        "_dep_scanner": attrs.source(default = "dev_buck//:ghc_dep_scan.py"),
    },
)

def _haskell_binary_impl(ctx: AnalysisContext) -> list[Provider]:
    out_bin = ctx.actions.declare_output(ctx.attrs.name)
    warnings_art = ctx.actions.declare_output(ctx.attrs.name + ".warnings.log")
    deps_json = ctx.actions.declare_output("__deps__.json")

    src_dirs = ctx.attrs.src_dirs or ["."]
    dep_info = _collect_haskell_deps(ctx.attrs.deps)

    cabal_macros_content = _generate_cabal_macros(ctx.attrs.name, "0.0.0", dep_info)
    cabal_macros = ctx.actions.write("cabal_macros.h", cabal_macros_content)

    pkg_dir_path = _get_pkg_dir_path(ctx.label)

    # Step 1: Scan module dependencies
    scan_args = cmd_args(
        "python3",
        ctx.attrs._dep_scanner,
        "--out",
        deps_json.as_output(),
        "--",
    )
    for d in src_dirs:
        scan_args.add("-i" + (pkg_dir_path + "/" + d if pkg_dir_path else d))
    if ctx.attrs.default_language:
        scan_args.add("-X" + ctx.attrs.default_language)
    for ext in ctx.attrs.default_extensions:
        scan_args.add("-X" + ext)
    scan_args.add(_build_ghc_dep_flags(dep_info))
    for flag in ctx.attrs.compiler_flags:
        scan_args.add(flag)
    scan_args.add("-optP-include", cmd_args(cabal_macros, format = "-optP{}"))
    scan_args.add(ctx.attrs.main)
    scan_args.add(ctx.attrs.srcs)

    ctx.actions.run(
        scan_args,
        category = "haskell_dep_scan",
        identifier = ctx.attrs.name,
    )

    # Step 2: Dynamic actions for compiling individual modules and linking
    def dynamic_compile(ctx: AnalysisContext, artifacts, outputs):
        dep_graph = artifacts[deps_json].read_json()

        src_map = {src.short_path: src for src in ctx.attrs.srcs}
        main_src = ctx.attrs.main
        src_map[main_src.short_path] = main_src

        modules = {}
        for mod_key, data in dep_graph.items():
            src_path = data["src"]
            matched_artifact = None
            for s_path, s_art in src_map.items():
                if src_path.endswith(s_path) or s_path.endswith(src_path):
                    matched_artifact = s_art
                    break
            if not matched_artifact:
                base = src_path.split("/")[-1]
                for s_path, s_art in src_map.items():
                    if s_path.endswith(base):
                        matched_artifact = s_art
                        break

            if matched_artifact:
                info = _parse_module_info(matched_artifact.short_path, src_dirs)
                modules[mod_key] = struct(
                    info = info,
                    src = matched_artifact,
                    deps = data.get("deps", []),
                )

        mod_dirs = {}
        for mod_key, mod in modules.items():
            mod_dirs[mod_key] = ctx.actions.declare_output("__mod__/" + mod.info.dotted_name, dir = True)

        # Compile each module in topological order
        ordered_keys = _topo_sort(modules)
        compiled_mod_dirs = []
        for mod_key in ordered_keys:
            mod = modules[mod_key]
            ghc_flags = []
            for d in src_dirs:
                ghc_flags.append("-i" + (pkg_dir_path + "/" + d if pkg_dir_path else d))

            for prev_dir in compiled_mod_dirs:
                ghc_flags.append(cmd_args(prev_dir, format = "-i{}"))

            ghc_flags.extend(_build_ghc_dep_flags(dep_info))

            if ctx.attrs.default_language:
                ghc_flags.append("-X" + ctx.attrs.default_language)
            for ext in ctx.attrs.default_extensions:
                ghc_flags.append("-X" + ext)
            for flag in ctx.attrs.compiler_flags:
                ghc_flags.append(flag)

            ghc_flags.append("-optP-include")
            ghc_flags.append(cmd_args(cabal_macros, format = "-optP{}"))

            compile_cmd = cmd_args(
                "bash",
                "-e",
                "-c",
                'out_dir="$1"; shift; src="$1"; shift; rel_path="$1"; shift; dir_path="$1"; shift; ' +
                'src_dir="$(dirname "$src")"; mkdir -p "$out_dir/$dir_path"; ' +
                'warn_file="$out_dir/$rel_path.warnings"; ' +
                'set +e; ghc -c "$src" -I"$src_dir" -o "$out_dir/$rel_path.o" -ohi "$out_dir/$rel_path.hi" "$@" 2> "$warn_file"; status=$?; ' +
                'if [ -s "$warn_file" ]; then cat "$warn_file" >&2; fi; exit $status',
                "--",
                mod_dirs[mod_key].as_output(),
                mod.src,
                mod.info.rel_path,
                mod.info.dir_path,
                ghc_flags,
            )

            ctx.actions.run(
                compile_cmd,
                category = "haskell_compile",
                identifier = mod.info.dotted_name,
            )
            compiled_mod_dirs.append(mod_dirs[mod_key])

        combine_warn_cmd = cmd_args(
            "bash",
            "-e",
            "-c",
            'out="$1"; shift; if [ "$#" -gt 0 ]; then find "$@" -name "*.warnings" -exec cat {} + > "$out" 2>/dev/null || true; fi; touch "$out"',
            "--",
            outputs[warnings_art].as_output(),
            [mod_dirs[k] for k in mod_dirs],
        )
        ctx.actions.run(
            combine_warn_cmd,
            category = "haskell_warnings",
            identifier = ctx.attrs.name,
        )

        # Step 3: Link binary
        link_cmd = cmd_args(
            "ghc",
            "-o",
            outputs[out_bin].as_output(),
        )
        for mod_key, mod in modules.items():
            link_cmd.add(cmd_args(mod_dirs[mod_key], format = "{}/" + mod.info.rel_path + ".o"))

        link_cmd.add(_build_ghc_dep_flags(dep_info))

        for flag in ctx.attrs.compiler_flags:
            link_cmd.add(flag)
        for el in dep_info.extra_libs:
            link_cmd.add("-l" + el)

        ctx.actions.run(
            link_cmd,
            category = "haskell_link",
            identifier = ctx.attrs.name,
        )

    ctx.actions.dynamic_output(
        dynamic = [deps_json],
        inputs = [ctx.attrs.main] + ctx.attrs.srcs + dep_info.pkg_dirs + [cabal_macros],
        outputs = [out_bin.as_output(), warnings_art.as_output()],
        f = dynamic_compile,
    )

    providers = [
        DefaultInfo(
            default_output = out_bin,
            sub_targets = {
                "warnings": [DefaultInfo(default_output = warnings_art)],
            },
        ),
        RunInfo(args = cmd_args(out_bin)),
    ]
    if getattr(ctx.attrs, "is_test", False):
        providers.append(
            ExternalRunnerTestInfo(
                type = "haskell",
                command = [out_bin],
            )
        )
    return providers

haskell_binary = rule(
    impl = _haskell_binary_impl,
    attrs = {
        "srcs": attrs.list(attrs.source(), default = []),
        "main": attrs.source(),
        "src_dirs": attrs.list(attrs.string(), default = []),
        "deps": attrs.list(attrs.dep(), default = []),
        "default_language": attrs.string(default = "Haskell2010"),
        "default_extensions": attrs.list(attrs.string(), default = []),
        "compiler_flags": attrs.list(attrs.string(), default = []),
        "is_test": attrs.bool(default = False),
        "_dep_scanner": attrs.source(default = "dev_buck//:ghc_dep_scan.py"),
    },
)

def _haskell_test_impl(ctx: AnalysisContext) -> list[Provider]:
    return _haskell_binary_impl(ctx)

haskell_test = rule(
    impl = _haskell_test_impl,
    attrs = {
        "srcs": attrs.list(attrs.source(), default = []),
        "main": attrs.source(),
        "src_dirs": attrs.list(attrs.string(), default = []),
        "deps": attrs.list(attrs.dep(), default = []),
        "default_language": attrs.string(default = "Haskell2010"),
        "default_extensions": attrs.list(attrs.string(), default = []),
        "compiler_flags": attrs.list(attrs.string(), default = []),
        "is_test": attrs.bool(default = True),
        "_dep_scanner": attrs.source(default = "dev_buck//:ghc_dep_scan.py"),
    },
)

def _haskell_lint_impl(ctx: AnalysisContext) -> list[Provider]:
    out = ctx.actions.declare_output("lint.ok")
    script = ctx.actions.declare_output("run_hlint_and_warnings.sh")
    script_lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        'OUT="$1"',
        "shift",
        'NUM_HINTS="$1"',
        "shift",
        "HINTS=()",
        'for ((i=0; i<NUM_HINTS; i++)); do',
        '  HINTS+=("--hint" "$1")',
        "  shift",
        "done",
        'NUM_DIAGS="$1"',
        "shift",
        "DIAGS=()",
        'for ((i=0; i<NUM_DIAGS; i++)); do',
        '  DIAGS+=("$1")',
        "  shift",
        "done",
        "failed=0",
        'if ! hlint "${HINTS[@]}" --threads "$@"; then',
        "  failed=1",
        "fi",
        'for diag in "${DIAGS[@]}"; do',
        '  if [ -s "$diag" ]; then',
        '    if grep -qi "warning:" "$diag"; then',
        '      echo "GHC compiler warning(s) detected:" >&2',
        '      cat "$diag" >&2',
        "      failed=1",
        "    fi",
        "  fi",
        "done",
        'if [ "$failed" -ne 0 ]; then',
        "  exit 1",
        "fi",
        'touch "$OUT"',
    ]
    ctx.actions.write(script, "\n".join(script_lines) + "\n", is_executable = True)

    diag_artifacts = []
    for t in ctx.attrs.targets:
        if "warnings" in t[DefaultInfo].sub_targets:
            diag_artifacts.extend(t[DefaultInfo].sub_targets["warnings"][DefaultInfo].default_outputs)

    cmd = cmd_args([
        script,
        out.as_output(),
        str(len(ctx.attrs.hints)),
    ])
    for h in ctx.attrs.hints:
        cmd.add(h)
    cmd.add(str(len(diag_artifacts)))
    for d in diag_artifacts:
        cmd.add(d)
    for s in ctx.attrs.srcs:
        cmd.add(s)

    ctx.actions.run(
        cmd,
        category = "haskell_lint",
    )

    return [DefaultInfo(default_output = out)]

haskell_lint = rule(
    impl = _haskell_lint_impl,
    attrs = {
        "hints": attrs.list(attrs.source(), default = [
            "root//dev-hlint:relude-hlint.yaml",
            "root//dev-hlint:base.yaml",
        ]),
        "srcs": attrs.list(attrs.source()),
        "targets": attrs.list(attrs.dep(), default = []),
    },
)


