import gleam/int
import gleam/list
import gleam/option.{type Option, None}
import lib_dataflow as dataflow
import lib_markup_aria_text as aria_text
import lib_markup_attributes as attr
import lib_markup_fragment as fragment
import lib_markup_html as html
import lib_styling as styling_api
import lib_styling_data as styling

pub type MathValue {
  MathLength(styling.Length)
  MathPercentage(styling.Pct)
}

pub type MathDisplay {
  MathBlock
  MathInline
}

pub type MathDir {
  MathLtr
  MathRtl
}

pub type MathVariant {
  MathNormal
}

pub type OperatorForm {
  FormInfix
  FormPostfix
  FormPrefix
}

pub type MathAttrs {
  MathAttrs(
    aria_atomic: dataflow.NodeOpt(Option(Bool)),
    aria_auto_complete: dataflow.NodeOpt(Option(html.AriaAutoComplete)),
    aria_busy: dataflow.NodeOpt(Option(Bool)),
    aria_checked: dataflow.NodeOpt(Option(html.AriaBoolMixedUndefined)),
    aria_col_count: dataflow.NodeOpt(Option(String)),
    aria_col_index: dataflow.NodeOpt(Option(String)),
    aria_col_span: dataflow.NodeOpt(Option(String)),
    aria_current: dataflow.NodeOpt(Option(html.AriaCurrent)),
    aria_description: dataflow.NodeOpt(Option(String)),
    aria_expanded: dataflow.NodeOpt(Option(html.AriaBoolUndefined)),
    aria_has_popup: dataflow.NodeOpt(Option(html.AriaHasPopup)),
    aria_hidden: dataflow.NodeOpt(Option(html.AriaBoolUndefined)),
    aria_invalid: dataflow.NodeOpt(Option(String)),
    aria_key_shortcuts: dataflow.NodeOpt(Option(String)),
    aria_label: dataflow.NodeOpt(Option(String)),
    aria_level: dataflow.NodeOpt(Option(String)),
    aria_live: dataflow.NodeOpt(Option(html.AriaLive)),
    aria_modal: dataflow.NodeOpt(Option(Bool)),
    aria_multi_line: dataflow.NodeOpt(Option(Bool)),
    aria_multi_selectable: dataflow.NodeOpt(Option(Bool)),
    aria_orientation: dataflow.NodeOpt(Option(html.AriaOrientation)),
    aria_placeholder: dataflow.NodeOpt(Option(String)),
    aria_pos_in_set: dataflow.NodeOpt(Option(String)),
    aria_pressed: dataflow.NodeOpt(Option(html.AriaBoolMixedUndefined)),
    aria_read_only: dataflow.NodeOpt(Option(Bool)),
    aria_required: dataflow.NodeOpt(Option(Bool)),
    aria_role_description: dataflow.NodeOpt(Option(String)),
    aria_row_count: dataflow.NodeOpt(Option(String)),
    aria_row_index: dataflow.NodeOpt(Option(String)),
    aria_row_span: dataflow.NodeOpt(Option(String)),
    aria_selected: dataflow.NodeOpt(Option(html.AriaBoolUndefined)),
    aria_set_size: dataflow.NodeOpt(Option(String)),
    aria_sort: dataflow.NodeOpt(Option(html.AriaSort)),
    aria_value_max: dataflow.NodeOpt(Option(String)),
    aria_value_min: dataflow.NodeOpt(Option(String)),
    aria_value_now: dataflow.NodeOpt(Option(String)),
    aria_value_text: dataflow.NodeOpt(Option(String)),
    id: dataflow.NodeOpt(Option(String)),
    aria_disabled: dataflow.NodeOpt(Option(Bool)),
    class_names: dataflow.NodeOpt(Option(List(String))),
    style: dataflow.NodeOpt(styling_api.AtomOpt),
    events: attr.Events,
    on_add: Option(fragment.OnAdd),
    alt_text: dataflow.NodeOpt(Option(String)),
    display: dataflow.NodeOpt(Option(MathDisplay)),
    display_style: dataflow.NodeOpt(Option(Bool)),
    math_dir: dataflow.NodeOpt(Option(MathDir)),
    nonce: dataflow.NodeOpt(Option(String)),
    role: dataflow.NodeOpt(Option(String)),
    slot: dataflow.NodeOpt(Option(String)),
    tab_index: dataflow.NodeOpt(Option(Int)),
    autofocus: dataflow.NodeOpt(Option(Bool)),
    script_level: dataflow.NodeOpt(Option(Int)),
    content: fragment.FragmentInput,
  )
}

pub fn math_attrs() -> MathAttrs {
  MathAttrs(
    aria_atomic: dataflow.literal(None),
    aria_auto_complete: dataflow.literal(None),
    aria_busy: dataflow.literal(None),
    aria_checked: dataflow.literal(None),
    aria_col_count: dataflow.literal(None),
    aria_col_index: dataflow.literal(None),
    aria_col_span: dataflow.literal(None),
    aria_current: dataflow.literal(None),
    aria_description: dataflow.literal(None),
    aria_expanded: dataflow.literal(None),
    aria_has_popup: dataflow.literal(None),
    aria_hidden: dataflow.literal(None),
    aria_invalid: dataflow.literal(None),
    aria_key_shortcuts: dataflow.literal(None),
    aria_label: dataflow.literal(None),
    aria_level: dataflow.literal(None),
    aria_live: dataflow.literal(None),
    aria_modal: dataflow.literal(None),
    aria_multi_line: dataflow.literal(None),
    aria_multi_selectable: dataflow.literal(None),
    aria_orientation: dataflow.literal(None),
    aria_placeholder: dataflow.literal(None),
    aria_pos_in_set: dataflow.literal(None),
    aria_pressed: dataflow.literal(None),
    aria_read_only: dataflow.literal(None),
    aria_required: dataflow.literal(None),
    aria_role_description: dataflow.literal(None),
    aria_row_count: dataflow.literal(None),
    aria_row_index: dataflow.literal(None),
    aria_row_span: dataflow.literal(None),
    aria_selected: dataflow.literal(None),
    aria_set_size: dataflow.literal(None),
    aria_sort: dataflow.literal(None),
    aria_value_max: dataflow.literal(None),
    aria_value_min: dataflow.literal(None),
    aria_value_now: dataflow.literal(None),
    aria_value_text: dataflow.literal(None),
    id: dataflow.literal(None),
    aria_disabled: dataflow.literal(None),
    class_names: dataflow.literal(None),
    nonce: dataflow.literal(None),
    role: dataflow.literal(None),
    slot: dataflow.literal(None),
    tab_index: dataflow.literal(None),
    autofocus: dataflow.literal(None),
    style: dataflow.literal(styling_api.empty()),
    events: attr.events(),
    on_add: None,
    alt_text: dataflow.literal(None),
    display: dataflow.literal(None),
    display_style: dataflow.literal(None),
    math_dir: dataflow.literal(None),
    script_level: dataflow.literal(None),
    content: fragment.EmptyInput,
  )
}

pub fn math(attrs: MathAttrs) -> fragment.Fragment {
  let MathAttrs(
    aria_atomic,
    aria_auto_complete,
    aria_busy,
    aria_checked,
    aria_col_count,
    aria_col_index,
    aria_col_span,
    aria_current,
    aria_description,
    aria_expanded,
    aria_has_popup,
    aria_hidden,
    aria_invalid,
    aria_key_shortcuts,
    aria_label,
    aria_level,
    aria_live,
    aria_modal,
    aria_multi_line,
    aria_multi_selectable,
    aria_orientation,
    aria_placeholder,
    aria_pos_in_set,
    aria_pressed,
    aria_read_only,
    aria_required,
    aria_role_description,
    aria_row_count,
    aria_row_index,
    aria_row_span,
    aria_selected,
    aria_set_size,
    aria_sort,
    aria_value_max,
    aria_value_min,
    aria_value_now,
    aria_value_text,
    id,
    aria_disabled,
    class_names,
    style,
    events,
    on_add,
    alt_text,
    display,
    display_style,
    math_dir,
    nonce,
    role,
    slot,
    tab_index,
    autofocus,
    script_level,
    content,
  ) = attrs
  let attrs =
    common_aria(
      aria_atomic,
      aria_auto_complete,
      aria_busy,
      aria_checked,
      aria_col_count,
      aria_col_index,
      aria_col_span,
      aria_current,
      aria_description,
      aria_expanded,
      aria_has_popup,
      aria_hidden,
      aria_invalid,
      aria_key_shortcuts,
      aria_label,
      aria_level,
      aria_live,
      aria_modal,
      aria_multi_line,
      aria_multi_selectable,
      aria_orientation,
      aria_placeholder,
      aria_pos_in_set,
      aria_pressed,
      aria_read_only,
      aria_required,
      aria_role_description,
      aria_row_count,
      aria_row_index,
      aria_row_span,
      aria_selected,
      aria_set_size,
      aria_sort,
      aria_value_max,
      aria_value_min,
      aria_value_now,
      aria_value_text,
      id,
      aria_disabled,
      class_names,
      nonce,
      role,
      slot,
      tab_index,
      autofocus,
      events,
    )
  let attrs = attr.add_style(attrs, style)
  let attrs = attr.add_events(attrs, events)
  let attrs = attr.add_on_add(attrs, on_add)
  let attrs =
    list.append(attrs, [
      fragment.ReactiveOptionalStringAttribute("alttext", alt_text),
      fragment.ReactiveOptionalStringAttribute(
        "display",
        attr.map_optional(display, display_text),
      ),
      fragment.ReactiveOptionalStringAttribute(
        "displaystyle",
        attr.map_optional(display_style, attr.bool_text),
      ),
      fragment.ReactiveOptionalStringAttribute(
        "dir",
        attr.map_optional(math_dir, math_dir_text),
      ),
      fragment.ReactiveOptionalStringAttribute(
        "scriptlevel",
        attr.map_optional(script_level, int.to_string),
      ),
    ])
  fragment.element_in(fragment.MathMl, "math", attrs, content)
}

pub type MiAttrs {
  MiAttrs(
    aria_atomic: dataflow.NodeOpt(Option(Bool)),
    aria_auto_complete: dataflow.NodeOpt(Option(html.AriaAutoComplete)),
    aria_busy: dataflow.NodeOpt(Option(Bool)),
    aria_checked: dataflow.NodeOpt(Option(html.AriaBoolMixedUndefined)),
    aria_col_count: dataflow.NodeOpt(Option(String)),
    aria_col_index: dataflow.NodeOpt(Option(String)),
    aria_col_span: dataflow.NodeOpt(Option(String)),
    aria_current: dataflow.NodeOpt(Option(html.AriaCurrent)),
    aria_description: dataflow.NodeOpt(Option(String)),
    aria_expanded: dataflow.NodeOpt(Option(html.AriaBoolUndefined)),
    aria_has_popup: dataflow.NodeOpt(Option(html.AriaHasPopup)),
    aria_hidden: dataflow.NodeOpt(Option(html.AriaBoolUndefined)),
    aria_invalid: dataflow.NodeOpt(Option(String)),
    aria_key_shortcuts: dataflow.NodeOpt(Option(String)),
    aria_label: dataflow.NodeOpt(Option(String)),
    aria_level: dataflow.NodeOpt(Option(String)),
    aria_live: dataflow.NodeOpt(Option(html.AriaLive)),
    aria_modal: dataflow.NodeOpt(Option(Bool)),
    aria_multi_line: dataflow.NodeOpt(Option(Bool)),
    aria_multi_selectable: dataflow.NodeOpt(Option(Bool)),
    aria_orientation: dataflow.NodeOpt(Option(html.AriaOrientation)),
    aria_placeholder: dataflow.NodeOpt(Option(String)),
    aria_pos_in_set: dataflow.NodeOpt(Option(String)),
    aria_pressed: dataflow.NodeOpt(Option(html.AriaBoolMixedUndefined)),
    aria_read_only: dataflow.NodeOpt(Option(Bool)),
    aria_required: dataflow.NodeOpt(Option(Bool)),
    aria_role_description: dataflow.NodeOpt(Option(String)),
    aria_row_count: dataflow.NodeOpt(Option(String)),
    aria_row_index: dataflow.NodeOpt(Option(String)),
    aria_row_span: dataflow.NodeOpt(Option(String)),
    aria_selected: dataflow.NodeOpt(Option(html.AriaBoolUndefined)),
    aria_set_size: dataflow.NodeOpt(Option(String)),
    aria_sort: dataflow.NodeOpt(Option(html.AriaSort)),
    aria_value_max: dataflow.NodeOpt(Option(String)),
    aria_value_min: dataflow.NodeOpt(Option(String)),
    aria_value_now: dataflow.NodeOpt(Option(String)),
    aria_value_text: dataflow.NodeOpt(Option(String)),
    id: dataflow.NodeOpt(Option(String)),
    aria_disabled: dataflow.NodeOpt(Option(Bool)),
    class_names: dataflow.NodeOpt(Option(List(String))),
    nonce: dataflow.NodeOpt(Option(String)),
    role: dataflow.NodeOpt(Option(String)),
    slot: dataflow.NodeOpt(Option(String)),
    tab_index: dataflow.NodeOpt(Option(Int)),
    autofocus: dataflow.NodeOpt(Option(Bool)),
    style: dataflow.NodeOpt(styling_api.AtomOpt),
    events: attr.Events,
    on_add: Option(fragment.OnAdd),
    display_style: dataflow.NodeOpt(Option(Bool)),
    math_dir: dataflow.NodeOpt(Option(MathDir)),
    script_level: dataflow.NodeOpt(Option(Int)),
    math_variant: dataflow.NodeOpt(Option(MathVariant)),
    content: fragment.FragmentInput,
  )
}

pub fn mi_attrs() -> MiAttrs {
  MiAttrs(
    aria_atomic: dataflow.literal(None),
    aria_auto_complete: dataflow.literal(None),
    aria_busy: dataflow.literal(None),
    aria_checked: dataflow.literal(None),
    aria_col_count: dataflow.literal(None),
    aria_col_index: dataflow.literal(None),
    aria_col_span: dataflow.literal(None),
    aria_current: dataflow.literal(None),
    aria_description: dataflow.literal(None),
    aria_expanded: dataflow.literal(None),
    aria_has_popup: dataflow.literal(None),
    aria_hidden: dataflow.literal(None),
    aria_invalid: dataflow.literal(None),
    aria_key_shortcuts: dataflow.literal(None),
    aria_label: dataflow.literal(None),
    aria_level: dataflow.literal(None),
    aria_live: dataflow.literal(None),
    aria_modal: dataflow.literal(None),
    aria_multi_line: dataflow.literal(None),
    aria_multi_selectable: dataflow.literal(None),
    aria_orientation: dataflow.literal(None),
    aria_placeholder: dataflow.literal(None),
    aria_pos_in_set: dataflow.literal(None),
    aria_pressed: dataflow.literal(None),
    aria_read_only: dataflow.literal(None),
    aria_required: dataflow.literal(None),
    aria_role_description: dataflow.literal(None),
    aria_row_count: dataflow.literal(None),
    aria_row_index: dataflow.literal(None),
    aria_row_span: dataflow.literal(None),
    aria_selected: dataflow.literal(None),
    aria_set_size: dataflow.literal(None),
    aria_sort: dataflow.literal(None),
    aria_value_max: dataflow.literal(None),
    aria_value_min: dataflow.literal(None),
    aria_value_now: dataflow.literal(None),
    aria_value_text: dataflow.literal(None),
    id: dataflow.literal(None),
    aria_disabled: dataflow.literal(None),
    class_names: dataflow.literal(None),
    nonce: dataflow.literal(None),
    role: dataflow.literal(None),
    slot: dataflow.literal(None),
    tab_index: dataflow.literal(None),
    autofocus: dataflow.literal(None),
    style: dataflow.literal(styling_api.empty()),
    events: attr.events(),
    on_add: None,
    display_style: dataflow.literal(None),
    math_dir: dataflow.literal(None),
    script_level: dataflow.literal(None),
    math_variant: dataflow.literal(None),
    content: fragment.EmptyInput,
  )
}

pub fn mi(attrs: MiAttrs) -> fragment.Fragment {
  let MiAttrs(
    aria_atomic,
    aria_auto_complete,
    aria_busy,
    aria_checked,
    aria_col_count,
    aria_col_index,
    aria_col_span,
    aria_current,
    aria_description,
    aria_expanded,
    aria_has_popup,
    aria_hidden,
    aria_invalid,
    aria_key_shortcuts,
    aria_label,
    aria_level,
    aria_live,
    aria_modal,
    aria_multi_line,
    aria_multi_selectable,
    aria_orientation,
    aria_placeholder,
    aria_pos_in_set,
    aria_pressed,
    aria_read_only,
    aria_required,
    aria_role_description,
    aria_row_count,
    aria_row_index,
    aria_row_span,
    aria_selected,
    aria_set_size,
    aria_sort,
    aria_value_max,
    aria_value_min,
    aria_value_now,
    aria_value_text,
    id,
    aria_disabled,
    class_names,
    nonce,
    role,
    slot,
    tab_index,
    autofocus,
    style,
    events,
    on_add,
    display_style,
    math_dir,
    script_level,
    math_variant,
    content,
  ) = attrs
  let attrs =
    common_aria(
      aria_atomic,
      aria_auto_complete,
      aria_busy,
      aria_checked,
      aria_col_count,
      aria_col_index,
      aria_col_span,
      aria_current,
      aria_description,
      aria_expanded,
      aria_has_popup,
      aria_hidden,
      aria_invalid,
      aria_key_shortcuts,
      aria_label,
      aria_level,
      aria_live,
      aria_modal,
      aria_multi_line,
      aria_multi_selectable,
      aria_orientation,
      aria_placeholder,
      aria_pos_in_set,
      aria_pressed,
      aria_read_only,
      aria_required,
      aria_role_description,
      aria_row_count,
      aria_row_index,
      aria_row_span,
      aria_selected,
      aria_set_size,
      aria_sort,
      aria_value_max,
      aria_value_min,
      aria_value_now,
      aria_value_text,
      id,
      aria_disabled,
      class_names,
      nonce,
      role,
      slot,
      tab_index,
      autofocus,
      events,
    )
  let attrs = attr.add_style(attrs, style)
  let attrs = attr.add_events(attrs, events)
  let attrs = attr.add_on_add(attrs, on_add)
  let attrs =
    list.append(attrs, [
      fragment.ReactiveOptionalStringAttribute(
        "displaystyle",
        attr.map_optional(display_style, attr.bool_text),
      ),
      fragment.ReactiveOptionalStringAttribute(
        "dir",
        attr.map_optional(math_dir, math_dir_text),
      ),
      fragment.ReactiveOptionalStringAttribute(
        "scriptlevel",
        attr.map_optional(script_level, int.to_string),
      ),
      fragment.ReactiveOptionalStringAttribute(
        "mathvariant",
        attr.map_optional(math_variant, math_variant_text),
      ),
    ])
  fragment.element_in(fragment.MathMl, "mi", attrs, content)
}

pub type MoAttrs {
  MoAttrs(
    aria_atomic: dataflow.NodeOpt(Option(Bool)),
    aria_auto_complete: dataflow.NodeOpt(Option(html.AriaAutoComplete)),
    aria_busy: dataflow.NodeOpt(Option(Bool)),
    aria_checked: dataflow.NodeOpt(Option(html.AriaBoolMixedUndefined)),
    aria_col_count: dataflow.NodeOpt(Option(String)),
    aria_col_index: dataflow.NodeOpt(Option(String)),
    aria_col_span: dataflow.NodeOpt(Option(String)),
    aria_current: dataflow.NodeOpt(Option(html.AriaCurrent)),
    aria_description: dataflow.NodeOpt(Option(String)),
    aria_expanded: dataflow.NodeOpt(Option(html.AriaBoolUndefined)),
    aria_has_popup: dataflow.NodeOpt(Option(html.AriaHasPopup)),
    aria_hidden: dataflow.NodeOpt(Option(html.AriaBoolUndefined)),
    aria_invalid: dataflow.NodeOpt(Option(String)),
    aria_key_shortcuts: dataflow.NodeOpt(Option(String)),
    aria_label: dataflow.NodeOpt(Option(String)),
    aria_level: dataflow.NodeOpt(Option(String)),
    aria_live: dataflow.NodeOpt(Option(html.AriaLive)),
    aria_modal: dataflow.NodeOpt(Option(Bool)),
    aria_multi_line: dataflow.NodeOpt(Option(Bool)),
    aria_multi_selectable: dataflow.NodeOpt(Option(Bool)),
    aria_orientation: dataflow.NodeOpt(Option(html.AriaOrientation)),
    aria_placeholder: dataflow.NodeOpt(Option(String)),
    aria_pos_in_set: dataflow.NodeOpt(Option(String)),
    aria_pressed: dataflow.NodeOpt(Option(html.AriaBoolMixedUndefined)),
    aria_read_only: dataflow.NodeOpt(Option(Bool)),
    aria_required: dataflow.NodeOpt(Option(Bool)),
    aria_role_description: dataflow.NodeOpt(Option(String)),
    aria_row_count: dataflow.NodeOpt(Option(String)),
    aria_row_index: dataflow.NodeOpt(Option(String)),
    aria_row_span: dataflow.NodeOpt(Option(String)),
    aria_selected: dataflow.NodeOpt(Option(html.AriaBoolUndefined)),
    aria_set_size: dataflow.NodeOpt(Option(String)),
    aria_sort: dataflow.NodeOpt(Option(html.AriaSort)),
    aria_value_max: dataflow.NodeOpt(Option(String)),
    aria_value_min: dataflow.NodeOpt(Option(String)),
    aria_value_now: dataflow.NodeOpt(Option(String)),
    aria_value_text: dataflow.NodeOpt(Option(String)),
    id: dataflow.NodeOpt(Option(String)),
    aria_disabled: dataflow.NodeOpt(Option(Bool)),
    class_names: dataflow.NodeOpt(Option(List(String))),
    nonce: dataflow.NodeOpt(Option(String)),
    role: dataflow.NodeOpt(Option(String)),
    slot: dataflow.NodeOpt(Option(String)),
    tab_index: dataflow.NodeOpt(Option(Int)),
    autofocus: dataflow.NodeOpt(Option(Bool)),
    style: dataflow.NodeOpt(styling_api.AtomOpt),
    events: attr.Events,
    on_add: Option(fragment.OnAdd),
    display_style: dataflow.NodeOpt(Option(Bool)),
    math_dir: dataflow.NodeOpt(Option(MathDir)),
    script_level: dataflow.NodeOpt(Option(Int)),
    fence: dataflow.NodeOpt(Option(Bool)),
    large_op: dataflow.NodeOpt(Option(Bool)),
    l_space: dataflow.NodeOpt(Option(MathValue)),
    max_size: dataflow.NodeOpt(Option(MathValue)),
    min_size: dataflow.NodeOpt(Option(MathValue)),
    moveable_limits: dataflow.NodeOpt(Option(Bool)),
    operator_form: dataflow.NodeOpt(Option(OperatorForm)),
    r_space: dataflow.NodeOpt(Option(MathValue)),
    separator: dataflow.NodeOpt(Option(Bool)),
    stretchy: dataflow.NodeOpt(Option(Bool)),
    symmetric: dataflow.NodeOpt(Option(Bool)),
    content: fragment.FragmentInput,
  )
}

pub fn mo_attrs() -> MoAttrs {
  MoAttrs(
    aria_atomic: dataflow.literal(None),
    aria_auto_complete: dataflow.literal(None),
    aria_busy: dataflow.literal(None),
    aria_checked: dataflow.literal(None),
    aria_col_count: dataflow.literal(None),
    aria_col_index: dataflow.literal(None),
    aria_col_span: dataflow.literal(None),
    aria_current: dataflow.literal(None),
    aria_description: dataflow.literal(None),
    aria_expanded: dataflow.literal(None),
    aria_has_popup: dataflow.literal(None),
    aria_hidden: dataflow.literal(None),
    aria_invalid: dataflow.literal(None),
    aria_key_shortcuts: dataflow.literal(None),
    aria_label: dataflow.literal(None),
    aria_level: dataflow.literal(None),
    aria_live: dataflow.literal(None),
    aria_modal: dataflow.literal(None),
    aria_multi_line: dataflow.literal(None),
    aria_multi_selectable: dataflow.literal(None),
    aria_orientation: dataflow.literal(None),
    aria_placeholder: dataflow.literal(None),
    aria_pos_in_set: dataflow.literal(None),
    aria_pressed: dataflow.literal(None),
    aria_read_only: dataflow.literal(None),
    aria_required: dataflow.literal(None),
    aria_role_description: dataflow.literal(None),
    aria_row_count: dataflow.literal(None),
    aria_row_index: dataflow.literal(None),
    aria_row_span: dataflow.literal(None),
    aria_selected: dataflow.literal(None),
    aria_set_size: dataflow.literal(None),
    aria_sort: dataflow.literal(None),
    aria_value_max: dataflow.literal(None),
    aria_value_min: dataflow.literal(None),
    aria_value_now: dataflow.literal(None),
    aria_value_text: dataflow.literal(None),
    id: dataflow.literal(None),
    aria_disabled: dataflow.literal(None),
    class_names: dataflow.literal(None),
    nonce: dataflow.literal(None),
    role: dataflow.literal(None),
    slot: dataflow.literal(None),
    tab_index: dataflow.literal(None),
    autofocus: dataflow.literal(None),
    style: dataflow.literal(styling_api.empty()),
    events: attr.events(),
    on_add: None,
    display_style: dataflow.literal(None),
    math_dir: dataflow.literal(None),
    script_level: dataflow.literal(None),
    fence: dataflow.literal(None),
    large_op: dataflow.literal(None),
    l_space: dataflow.literal(None),
    max_size: dataflow.literal(None),
    min_size: dataflow.literal(None),
    moveable_limits: dataflow.literal(None),
    operator_form: dataflow.literal(None),
    r_space: dataflow.literal(None),
    separator: dataflow.literal(None),
    stretchy: dataflow.literal(None),
    symmetric: dataflow.literal(None),
    content: fragment.EmptyInput,
  )
}

pub fn mo(attrs: MoAttrs) -> fragment.Fragment {
  let MoAttrs(
    aria_atomic,
    aria_auto_complete,
    aria_busy,
    aria_checked,
    aria_col_count,
    aria_col_index,
    aria_col_span,
    aria_current,
    aria_description,
    aria_expanded,
    aria_has_popup,
    aria_hidden,
    aria_invalid,
    aria_key_shortcuts,
    aria_label,
    aria_level,
    aria_live,
    aria_modal,
    aria_multi_line,
    aria_multi_selectable,
    aria_orientation,
    aria_placeholder,
    aria_pos_in_set,
    aria_pressed,
    aria_read_only,
    aria_required,
    aria_role_description,
    aria_row_count,
    aria_row_index,
    aria_row_span,
    aria_selected,
    aria_set_size,
    aria_sort,
    aria_value_max,
    aria_value_min,
    aria_value_now,
    aria_value_text,
    id,
    aria_disabled,
    class_names,
    nonce,
    role,
    slot,
    tab_index,
    autofocus,
    style,
    events,
    on_add,
    display_style,
    math_dir,
    script_level,
    fence,
    large_op,
    l_space,
    max_size,
    min_size,
    moveable_limits,
    operator_form,
    r_space,
    separator,
    stretchy,
    symmetric,
    content,
  ) = attrs
  let attrs =
    common_aria(
      aria_atomic,
      aria_auto_complete,
      aria_busy,
      aria_checked,
      aria_col_count,
      aria_col_index,
      aria_col_span,
      aria_current,
      aria_description,
      aria_expanded,
      aria_has_popup,
      aria_hidden,
      aria_invalid,
      aria_key_shortcuts,
      aria_label,
      aria_level,
      aria_live,
      aria_modal,
      aria_multi_line,
      aria_multi_selectable,
      aria_orientation,
      aria_placeholder,
      aria_pos_in_set,
      aria_pressed,
      aria_read_only,
      aria_required,
      aria_role_description,
      aria_row_count,
      aria_row_index,
      aria_row_span,
      aria_selected,
      aria_set_size,
      aria_sort,
      aria_value_max,
      aria_value_min,
      aria_value_now,
      aria_value_text,
      id,
      aria_disabled,
      class_names,
      nonce,
      role,
      slot,
      tab_index,
      autofocus,
      events,
    )
  let attrs = attr.add_style(attrs, style)
  let attrs = attr.add_events(attrs, events)
  let attrs = attr.add_on_add(attrs, on_add)
  let attrs =
    list.append(attrs, [
      fragment.ReactiveOptionalStringAttribute(
        "displaystyle",
        attr.map_optional(display_style, attr.bool_text),
      ),
      fragment.ReactiveOptionalStringAttribute(
        "dir",
        attr.map_optional(math_dir, math_dir_text),
      ),
      fragment.ReactiveOptionalStringAttribute(
        "scriptlevel",
        attr.map_optional(script_level, int.to_string),
      ),
      fragment.ReactiveOptionalStringAttribute(
        "fence",
        attr.map_optional(fence, attr.bool_text),
      ),
      fragment.ReactiveOptionalStringAttribute(
        "largeop",
        attr.map_optional(large_op, attr.bool_text),
      ),
      fragment.ReactiveOptionalStringAttribute(
        "lspace",
        attr.map_optional(l_space, value_text),
      ),
      fragment.ReactiveOptionalStringAttribute(
        "maxsize",
        attr.map_optional(max_size, value_text),
      ),
      fragment.ReactiveOptionalStringAttribute(
        "minsize",
        attr.map_optional(min_size, value_text),
      ),
      fragment.ReactiveOptionalStringAttribute(
        "movablelimits",
        attr.map_optional(moveable_limits, attr.bool_text),
      ),
      fragment.ReactiveOptionalStringAttribute(
        "form",
        attr.map_optional(operator_form, operator_form_text),
      ),
      fragment.ReactiveOptionalStringAttribute(
        "rspace",
        attr.map_optional(r_space, value_text),
      ),
      fragment.ReactiveOptionalStringAttribute(
        "separator",
        attr.map_optional(separator, attr.bool_text),
      ),
      fragment.ReactiveOptionalStringAttribute(
        "stretchy",
        attr.map_optional(stretchy, attr.bool_text),
      ),
      fragment.ReactiveOptionalStringAttribute(
        "symmetric",
        attr.map_optional(symmetric, attr.bool_text),
      ),
    ])
  fragment.element_in(fragment.MathMl, "mo", attrs, content)
}

fn common_aria(
  aria_atomic: dataflow.NodeOpt(Option(Bool)),
  aria_auto_complete: dataflow.NodeOpt(Option(html.AriaAutoComplete)),
  aria_busy: dataflow.NodeOpt(Option(Bool)),
  aria_checked: dataflow.NodeOpt(Option(html.AriaBoolMixedUndefined)),
  aria_col_count: dataflow.NodeOpt(Option(String)),
  aria_col_index: dataflow.NodeOpt(Option(String)),
  aria_col_span: dataflow.NodeOpt(Option(String)),
  aria_current: dataflow.NodeOpt(Option(html.AriaCurrent)),
  aria_description: dataflow.NodeOpt(Option(String)),
  aria_expanded: dataflow.NodeOpt(Option(html.AriaBoolUndefined)),
  aria_has_popup: dataflow.NodeOpt(Option(html.AriaHasPopup)),
  aria_hidden: dataflow.NodeOpt(Option(html.AriaBoolUndefined)),
  aria_invalid: dataflow.NodeOpt(Option(String)),
  aria_key_shortcuts: dataflow.NodeOpt(Option(String)),
  aria_label: dataflow.NodeOpt(Option(String)),
  aria_level: dataflow.NodeOpt(Option(String)),
  aria_live: dataflow.NodeOpt(Option(html.AriaLive)),
  aria_modal: dataflow.NodeOpt(Option(Bool)),
  aria_multi_line: dataflow.NodeOpt(Option(Bool)),
  aria_multi_selectable: dataflow.NodeOpt(Option(Bool)),
  aria_orientation: dataflow.NodeOpt(Option(html.AriaOrientation)),
  aria_placeholder: dataflow.NodeOpt(Option(String)),
  aria_pos_in_set: dataflow.NodeOpt(Option(String)),
  aria_pressed: dataflow.NodeOpt(Option(html.AriaBoolMixedUndefined)),
  aria_read_only: dataflow.NodeOpt(Option(Bool)),
  aria_required: dataflow.NodeOpt(Option(Bool)),
  aria_role_description: dataflow.NodeOpt(Option(String)),
  aria_row_count: dataflow.NodeOpt(Option(String)),
  aria_row_index: dataflow.NodeOpt(Option(String)),
  aria_row_span: dataflow.NodeOpt(Option(String)),
  aria_selected: dataflow.NodeOpt(Option(html.AriaBoolUndefined)),
  aria_set_size: dataflow.NodeOpt(Option(String)),
  aria_sort: dataflow.NodeOpt(Option(html.AriaSort)),
  aria_value_max: dataflow.NodeOpt(Option(String)),
  aria_value_min: dataflow.NodeOpt(Option(String)),
  aria_value_now: dataflow.NodeOpt(Option(String)),
  aria_value_text: dataflow.NodeOpt(Option(String)),
  id: dataflow.NodeOpt(Option(String)),
  aria_disabled: dataflow.NodeOpt(Option(Bool)),
  class_names: dataflow.NodeOpt(Option(List(String))),
  nonce: dataflow.NodeOpt(Option(String)),
  role: dataflow.NodeOpt(Option(String)),
  slot: dataflow.NodeOpt(Option(String)),
  tab_index: dataflow.NodeOpt(Option(Int)),
  autofocus: dataflow.NodeOpt(Option(Bool)),
  events: attr.Events,
) -> List(fragment.Attribute) {
  attr.common_reactive_aria(
    attr.map_optional(aria_atomic, attr.bool_text),
    attr.map_optional(aria_auto_complete, aria_text.auto_complete),
    attr.map_optional(aria_busy, attr.bool_text),
    attr.map_optional(aria_checked, aria_text.bool_mixed_undefined),
    aria_col_count,
    aria_col_index,
    aria_col_span,
    attr.map_optional(aria_current, aria_text.current),
    aria_description,
    attr.map_optional(aria_expanded, aria_text.bool_undefined),
    attr.map_optional(aria_has_popup, aria_text.has_popup),
    attr.map_optional(aria_hidden, aria_text.bool_undefined),
    aria_invalid,
    aria_key_shortcuts,
    aria_label,
    aria_level,
    attr.map_optional(aria_live, aria_text.live),
    attr.map_optional(aria_modal, attr.bool_text),
    attr.map_optional(aria_multi_line, attr.bool_text),
    attr.map_optional(aria_multi_selectable, attr.bool_text),
    attr.map_optional(aria_orientation, aria_text.orientation),
    aria_placeholder,
    aria_pos_in_set,
    attr.map_optional(aria_pressed, aria_text.bool_mixed_undefined),
    attr.map_optional(aria_read_only, attr.bool_text),
    attr.map_optional(aria_required, attr.bool_text),
    aria_role_description,
    aria_row_count,
    aria_row_index,
    aria_row_span,
    attr.map_optional(aria_selected, aria_text.bool_undefined),
    aria_set_size,
    attr.map_optional(aria_sort, aria_text.sort),
    aria_value_max,
    aria_value_min,
    aria_value_now,
    aria_value_text,
    id,
    aria_disabled,
    class_names,
    nonce,
    role,
    slot,
    tab_index,
    autofocus,
    events,
  )
}

fn value_text(value: MathValue) -> String {
  case value {
    MathLength(value) -> styling.length_text(value)
    MathPercentage(value) -> styling.percentage_text(value)
  }
}

// These entry points preserve the source's element-dependent portal records
// without exposing the internal fragment attribute representation.
pub fn portal(node: fragment.Node, attrs: MathAttrs) -> fragment.Fragment {
  to_portal(node, math(attrs))
}

pub fn portal_mi(node: fragment.Node, attrs: MiAttrs) -> fragment.Fragment {
  to_portal(node, mi(attrs))
}

pub fn portal_mo(node: fragment.Node, attrs: MoAttrs) -> fragment.Fragment {
  to_portal(node, mo(attrs))
}

fn to_portal(
  node: fragment.Node,
  value: fragment.Fragment,
) -> fragment.Fragment {
  case value {
    fragment.ElementNode(_, _, attributes, content) ->
      fragment.PortalNode(node, attributes, content)
    _ -> panic as "expected an element fragment"
  }
}

fn display_text(value: MathDisplay) -> String {
  case value {
    MathBlock -> "block"
    MathInline -> "inline"
  }
}

fn math_dir_text(value: MathDir) -> String {
  case value {
    MathLtr -> "ltr"
    MathRtl -> "rtl"
  }
}

fn math_variant_text(value: MathVariant) -> String {
  case value {
    MathNormal -> "normal"
  }
}

fn operator_form_text(value: OperatorForm) -> String {
  case value {
    FormInfix -> "infix"
    FormPostfix -> "postfix"
    FormPrefix -> "prefix"
  }
}
