# Do not manually edit this file, it is managed by Gleam.
#
# This file locks the dependency versions used, to make your build
# deterministic and to prevent unexpected versions from being included
# in your application.
#
# You should check this file into your source control repository.

packages = [
  { name = "gleam_stdlib", version = "1.0.5", build_tools = ["gleam"], requirements = [], source = "local", path = "../vendor/gleam_stdlib-1.0.5" },
  { name = "symbolize_lib_hex", version = "0.1.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], source = "local", path = "../lib-hex" },
]

[requirements]
gleam_stdlib = { path = "../vendor/gleam_stdlib-1.0.5" }
symbolize_lib_hex = { path = "../lib-hex" }
