run: when_changed
tasks:
  check:
    cmd: buck2 build //lib-hex:check
  format:check:
    aliases:
    - fc
    cmd: buck2 build //lib-hex:format-check
  lint:
    aliases:
    - l
    cmd: buck2 build //lib-hex:lint
  test:debug:
    aliases:
    - test
    - t
    cmd: buck2 test -m debug //lib-hex:test
  test:release:
    aliases:
    - tr
    cmd: buck2 test -m release //lib-hex:test
version: '3'
