run: when_changed
tasks:
  check:
    cmd: buck2 build //lib-dataflow:check
  format:check:
    aliases:
    - fc
    cmd: buck2 build //lib-dataflow:format-check
  test:browser:
    deps:
    - build
    dir: '{{.TASKFILE_DIR}}/../dev-browser-test'
    cmd: gleam run --module lib_dataflow_browser_driver_main
  build:
    dir: '{{.TASKFILE_DIR}}'
    cmd: gleam build
  lint:
    aliases:
    - l
    cmd: buck2 build //lib-dataflow:lint
  test:debug:
    aliases:
    - test
    - t
    cmd: buck2 test -m debug //lib-dataflow:test
  test:release:
    aliases:
    - tr
    cmd: buck2 test -m release //lib-dataflow:test
version: '3'
