run: when_changed
tasks:
  check:
    cmd: buck2 build //lib-test:check
  format:check:
    aliases:
    - fc
    cmd: buck2 build //lib-test:format-check
  link-build-dir:
    cmd:
      task: :build-dir:link-package-build-dir
      vars:
        NAME: '{{.NAME}}'
  lint:
    aliases:
    - l
    cmd: buck2 build //lib-test:lint
  test:debug:
    aliases:
    - test
    - t
    cmd: buck2 test -m debug //lib-test:test
  test:release:
    aliases:
    - tr
    cmd: buck2 test -m release //lib-test:test
vars:
  NAME: lib-test
version: '3'
