name = "symbolize_lib_collection"
version = "0.1.0"
target = "javascript"
gleam = ">= 1.18.1 and < 2.0.0"

[javascript]
runtime = "node"
source_maps = true

[dependencies]
gleam_stdlib = { path = "../vendor/gleam_stdlib-1.0.5" }
