run: when_changed
tasks:
  check:
    cmd: buck2 build //lib-collection:check
  format:check:
    aliases:
    - fc
    cmd: buck2 build //lib-collection:format-check
  lint:
    aliases:
    - l
    cmd: buck2 build //lib-collection:lint
  test:debug:
    aliases:
    - test
    - t
    cmd: buck2 test -m debug //lib-collection:test
  test:release:
    aliases:
    - tr
    cmd: buck2 test -m release //lib-collection:test
version: '3'
