# Do not manually edit this file, it is managed by Gleam.
#
# This file locks the dependency versions used, to make your build
# deterministic and to prevent unexpected versions from being included
# in your application.
#
# You should check this file into your source control repository.

packages = [
  { name = "gleam_stdlib", version = "1.0.5", build_tools = ["gleam"], requirements = [], otp_app = "gleam_stdlib", source = "hex", outer_checksum = "CEE5B6C076A85B45F60C585F4316C63EC8B7127C119D5738C3958A9C4D50404E" },
  { name = "symbolize_dev_browser_test", version = "0.1.0", build_tools = ["gleam"], requirements = ["gleam_stdlib", "symbolize_lib_dataflow"], source = "local", path = "../dev-browser-test" },
  { name = "symbolize_lib_dataflow", version = "0.1.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], source = "local", path = "../lib-dataflow" },
  { name = "symbolize_lib_error", version = "0.1.0", build_tools = ["gleam"], requirements = ["gleam_stdlib", "symbolize_dev_browser_test", "symbolize_lib_dataflow", "symbolize_lib_random", "symbolize_lib_time"], source = "local", path = "../lib-error" },
  { name = "symbolize_lib_hex", version = "0.1.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], source = "local", path = "../lib-hex" },
  { name = "symbolize_lib_random", version = "0.1.0", build_tools = ["gleam"], requirements = ["gleam_stdlib", "symbolize_lib_hex"], source = "local", path = "../lib-random" },
  { name = "symbolize_lib_test", version = "0.1.0", build_tools = ["gleam"], requirements = ["gleam_stdlib", "symbolize_lib_dataflow", "symbolize_lib_error"], source = "local", path = "../lib-test" },
  { name = "symbolize_lib_time", version = "0.1.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], source = "local", path = "../lib-time" },
]

[requirements]
gleam_stdlib = { version = ">= 1.0.5 and < 2.0.0" }
symbolize_lib_test = { path = "../lib-test" }
symbolize_lib_time = { path = "../lib-time" }
