run: when_changed
tasks:
  check:
    cmd: buck2 build //lib-test-runner:check
  format:check:
    aliases:
    - fc
    cmd: buck2 build //lib-test-runner:format-check
  build:
    dir: '{{.TASKFILE_DIR}}'
    cmd: gleam build
  lint:
    aliases:
    - l
    cmd: buck2 build //lib-test-runner:lint
  test:debug:
    aliases:
    - test
    - t
    cmd: buck2 test -m debug //lib-test-runner:test
  test:release:
    aliases:
    - tr
    cmd: buck2 test -m release //lib-test-runner:test
version: '3'
