run: when_changed
tasks:
  check:
    cmd: buck2 build //svc-auth-guest-view:check
  format:check:
    aliases:
    - fc
    cmd: buck2 build //svc-auth-guest-view:format-check
  build:
    dir: '{{.TASKFILE_DIR}}'
    cmd: gleam build
  test:browser:
    deps:
    - build
    dir: '{{.TASKFILE_DIR}}'
    cmd: gleam run --module svc_auth_guest_view_browser_driver_main
  lint:
    aliases:
    - l
    cmd: buck2 build //svc-auth-guest-view:lint
version: '3'
