run: when_changed
tasks:
  check:
    cmd: buck2 build //lib-time:check
  format:check:
    aliases:
    - fc
    cmd: buck2 build //lib-time:format-check
  build:
    dir: '{{.TASKFILE_DIR}}'
    cmd: gleam build
  test:browser:
    deps:
    - build
    dir: '{{.TASKFILE_DIR}}/../dev-browser-test'
    cmd: gleam run --module lib_time_browser_driver_main
  lint:
    aliases:
    - l
    cmd: buck2 build //lib-time:lint
  test:debug:
    aliases:
    - test
    - t
    cmd: buck2 test -m debug //lib-time:test
  test:release:
    aliases:
    - tr
    cmd: buck2 test -m release //lib-time:test
version: '3'
