load("@dev_buck//:gleam.bzl", "gleam_package")

gleam_package(
    name = "dev-node-test",
    package_name = "symbolize_dev_node_test",
    deps = [
        "//lib-collection:lib-collection",
        "//lib-dataflow:lib-dataflow",
        "//lib-error:lib-error",
        "//lib-hex:lib-hex",
        "//lib-markup:lib-markup",
        "//lib-payload:lib-payload",
        "//lib-random:lib-random",
        "//lib-stream:lib-stream",
        "//lib-styling:lib-styling",
        "//lib-time:lib-time",
        "vendor//:gleam_stdlib",
    ],
)

