run: when_changed
tasks:
  check:
    cmd: buck2 build //dev-node-test:check
  format:check:
    aliases:
    - fc
    cmd: buck2 build //dev-node-test:format-check
  build:
    dir: '{{.TASKFILE_DIR}}'
    cmd: gleam build
  lint:
    aliases:
    - l
    cmd: buck2 build //dev-node-test:lint
  test:debug:
    aliases:
    - test
    - t
    cmd: buck2 test -m debug //dev-node-test:test
  test:release:
    aliases:
    - tr
    cmd: buck2 test -m release //dev-node-test:test
version: '3'
