version: '3'
run: when_changed
tasks:
  check:
    cmd: buck2 build //lib-stream:check
  format:check:
    aliases:
    - fc
    cmd: buck2 build //lib-stream:format-check
  test:http:
    deps:
    - build
    dir: '{{.TASKFILE_DIR}}'
    cmd: gleam run --module lib_stream_http_driver_main
  test:custom:
    deps:
    - build
    dir: '{{.TASKFILE_DIR}}'
    cmd: gleam run --module lib_stream_custom_http_driver_main
  build:
    dir: '{{.TASKFILE_DIR}}'
    cmd: gleam build
  test:browser:
    deps:
    - build
    dir: '{{.TASKFILE_DIR}}'
    cmd: gleam run --module lib_stream_browser_driver_main
  lint:
    aliases:
    - l
    cmd: buck2 build //lib-stream:lint
  test:debug:
    aliases:
    - test
    - t
    cmd: buck2 test -m debug //lib-stream:test
  test:release:
    aliases:
    - tr
    cmd: buck2 test -m release //lib-stream:test
