version: '3'
run: when_changed
tasks:
  check:
    dir: '{{.TASKFILE_DIR}}'
    cmd: gleam check
  format:check:
    dir: '{{.TASKFILE_DIR}}'
    cmd: gleam format --check src
  test:
    deps:
      - build
    dir: '{{.TASKFILE_DIR}}'
    cmd: gleam run --module lib_stream_test_main
  test:http:
    deps:
      - build
    dir: '{{.TASKFILE_DIR}}'
    cmd: gleam run --module lib_stream_http_driver_main
  test:custom:
    deps:
      - build
    dir: '{{.TASKFILE_DIR}}'
    cmd: gleam run --module lib_stream_custom_http_driver_main
  build:
    dir: '{{.TASKFILE_DIR}}'
    cmd: gleam build
  test:browser:
    deps:
      - build
    dir: '{{.TASKFILE_DIR}}'
    cmd: gleam run --module lib_stream_browser_driver_main
  link-build-dir:
    cmd:
      task: :build-dir:link-package-build-dir
      vars:
        NAME: '{{.NAME}}'
vars:
  NAME: lib-stream
